(ns masr.resources.-expr7-2ef3822.Assignment.Assignment_14553)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_14493",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/Cast,
                                                    :arg
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/FunctionCall,
                                                                              :symbol-ref
                                                                              #:masr.specs{:identifier
                                                                                           "pow__AT____lpython_overloaded_0__pow",
                                                                                           :symtab-id
                                                                                           2},
                                                                              :orig-symref
                                                                              #:masr.specs{:identifier
                                                                                           "pow",
                                                                                           :symtab-id
                                                                                           2},
                                                                              :call-args
                                                                              [[#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:Integer
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Integer,
                                                                                                                                    :integer-kind
                                                                                                                                    4,
                                                                                                                                    :dimension*
                                                                                                                                    []}},
                                                                                                          :int
                                                                                                          2,
                                                                                                          :expr-head
                                                                                                          :masr.specs/IntegerConstant}}]
                                                                               [#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:Integer
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Integer,
                                                                                                                                    :integer-kind
                                                                                                                                    4,
                                                                                                                                    :dimension*
                                                                                                                                    []}},
                                                                                                          :int
                                                                                                          2,
                                                                                                          :expr-head
                                                                                                          :masr.specs/IntegerConstant}}]],
                                                                              :return-type
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        8,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:float
                                                                                                        4.0,
                                                                                                        :expr-head
                                                                                                        :masr.specs/RealConstant,
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :dt?
                                                                              ()}},
                                                    :cast-kind
                                                    #:masr.specs{:term
                                                                 :masr.specs/cast-kind,
                                                                 :cast-kind-enum
                                                                 "RealToInteger"},
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Integer,
                                                                              :integer-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:Integer
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :int
                                                                              4,
                                                                              :expr-head
                                                                              :masr.specs/IntegerConstant}}}},
                          :overloaded ()}}

