(ns masr.resources.-test_builtin_len-922cf65.Assignment.Assignment_32907)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_32808",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/TupleConstant,
                                                    :elements
                                                    [#:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:Integer
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :int
                                                                               1,
                                                                               :expr-head
                                                                               :masr.specs/IntegerConstant}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:Integer
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :int
                                                                               2,
                                                                               :expr-head
                                                                               :masr.specs/IntegerConstant}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringConstant,
                                                                               :string
                                                                               "a",
                                                                               :Character
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Character,
                                                                                                         :character-kind
                                                                                                         1,
                                                                                                         :len
                                                                                                         1,
                                                                                                         :disposition
                                                                                                         "compile-time-length",
                                                                                                         :len-expr?
                                                                                                         (),
                                                                                                         :dimension*
                                                                                                         []}}}}],
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Tuple,
                                                                              :ttype*
                                                                              [#:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}}
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}}
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Character,
                                                                                                         :character-kind
                                                                                                         1,
                                                                                                         :len
                                                                                                         1,
                                                                                                         :disposition
                                                                                                         "compile-time-length",
                                                                                                         :len-expr?
                                                                                                         (),
                                                                                                         :dimension*
                                                                                                         []}}]}}}},
                          :overloaded ()}}

