(ns masr.resources.-test_builtin_len-922cf65.Assignment.Assignment_32898)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_32778",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/ListConstant,
                                                    :expr*
                                                    [#:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:float
                                                                               1.2,
                                                                               :expr-head
                                                                               :masr.specs/RealConstant,
                                                                               :Real
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Real,
                                                                                                         :real-kind
                                                                                                         8,
                                                                                                         :dimension*
                                                                                                         []}}}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:float
                                                                               3.4,
                                                                               :expr-head
                                                                               :masr.specs/RealConstant,
                                                                               :Real
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Real,
                                                                                                         :real-kind
                                                                                                         8,
                                                                                                         :dimension*
                                                                                                         []}}}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:float
                                                                               5.6,
                                                                               :expr-head
                                                                               :masr.specs/RealConstant,
                                                                               :Real
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Real,
                                                                                                         :real-kind
                                                                                                         8,
                                                                                                         :dimension*
                                                                                                         []}}}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:float
                                                                               7.8,
                                                                               :expr-head
                                                                               :masr.specs/RealConstant,
                                                                               :Real
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Real,
                                                                                                         :real-kind
                                                                                                         8,
                                                                                                         :dimension*
                                                                                                         []}}}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:float
                                                                               9.0,
                                                                               :expr-head
                                                                               :masr.specs/RealConstant,
                                                                               :Real
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Real,
                                                                                                         :real-kind
                                                                                                         8,
                                                                                                         :dimension*
                                                                                                         []}}}}],
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/List,
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        8,
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

