(ns masr.resources.-test_builtin_len-922cf65.Assignment.Assignment_32895)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_32772",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/ListConstant,
                                                    :expr*
                                                    [#:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:Integer
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :int
                                                                               1,
                                                                               :expr-head
                                                                               :masr.specs/IntegerConstant}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:Integer
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :int
                                                                               2,
                                                                               :expr-head
                                                                               :masr.specs/IntegerConstant}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:Integer
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :int
                                                                               3,
                                                                               :expr-head
                                                                               :masr.specs/IntegerConstant}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:Integer
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/Integer,
                                                                                                         :integer-kind
                                                                                                         4,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :int
                                                                               4,
                                                                               :expr-head
                                                                               :masr.specs/IntegerConstant}}],
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/List,
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

