(ns masr.resources.-expr_09-0e8c1e6.Function.Function_20808)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_20739"
                           "Assignment_20742"
                           "Assignment_20745"
                           "Assignment_20748"
                           "Assignment_20751"
                           "Assignment_20754"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               "Var_20565",
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               "Var_20568",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               "Var_20571",
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               "Var_20574",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               "Var_20577",
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Integer
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :int
                                                                                                         10,
                                                                                                         :expr-head
                                                                                                         :masr.specs/IntegerConstant}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_20757"
                           "Assignment_20760"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    "Var_20586",
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              23.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         1.0E-6,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    "Var_20589",
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              23.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         0.0,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    "Var_20592",
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              6.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         1.0E-6,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    "Var_20595",
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              6.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         0.0,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_20763"
                           "Assignment_20766"
                           "DoLoop_20778"
                           "Assignment_20769"
                           "Assignment_20772"
                           "DoLoop_20781"],
                          :dependencies [],
                          :deterministic false,
                          :function-signature "FunctionType_20718",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 3,
                                       :hash-map
                                       {:y "Variable_20676",
                                        :e "Variable_20679",
                                        :k "Variable_20682",
                                        :g "Variable_20685",
                                        :c "Variable_20688",
                                        :j "Variable_20691",
                                        :b "Variable_20694",
                                        :d "Variable_20697",
                                        :x "Variable_20700",
                                        :i "Variable_20703",
                                        :a "Variable_20706"}},
                          :function-name "test_multiple_assign_1"}}

