(ns masr.resources.-test_builtin_str-fcdedc2.Function.Function_37554)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_37467"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "123",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   3,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37203",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37470"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "12345",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   5,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37209",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37473"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "-12",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   3,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37215",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37476"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "-121212",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   7,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37221",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37479"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37227",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "RealToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "12.322234",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   9,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37482"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37233",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "RealToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "12.322234",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   9,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37485"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37239",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "LogicalToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "True",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   4,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37488"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_37245",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "LogicalToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "False",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   5,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_37491"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               "Var_37251",
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               "Var_37254",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}],
                          :dependencies [],
                          :deterministic false,
                          :function-signature "FunctionType_37455",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 3,
                                       :hash-map
                                       {:bool_t "Variable_37404",
                                        :str_t "Variable_37407",
                                        :x "Variable_37410",
                                        :xx "Variable_37413",
                                        :yy "Variable_37416"}},
                          :function-name "str_conv_for_variables"}}

