(ns masr.resources.-test_numpy_03-6dd742e.Assignment.Assignment_47640)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_45897",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/IntegerBinOp,
                                                    :integer-left
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/IntegerBinOp,
                                                                              :integer-left
                                                                              "Var_45900",
                                                                              :integer-binop
                                                                              #:masr.specs{:integer-binop-enum
                                                                                           "Sub",
                                                                                           :term
                                                                                           :masr.specs/integer-binop},
                                                                              :integer-right
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/IntegerBinOp,
                                                                                                        :integer-left
                                                                                                        "Var_45903",
                                                                                                        :integer-binop
                                                                                                        #:masr.specs{:integer-binop-enum
                                                                                                                     "Mul",
                                                                                                                     :term
                                                                                                                     :masr.specs/integer-binop},
                                                                                                        :integer-right
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/expr,
                                                                                                                     :asr-expr-head
                                                                                                                     #:masr.specs{:Integer
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/ttype,
                                                                                                                                               :asr-ttype-head
                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                            :masr.specs/Integer,
                                                                                                                                                            :integer-kind
                                                                                                                                                            4,
                                                                                                                                                            :dimension*
                                                                                                                                                            []}},
                                                                                                                                  :int
                                                                                                                                  256,
                                                                                                                                  :expr-head
                                                                                                                                  :masr.specs/IntegerConstant}},
                                                                                                        :Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :integer-value?
                                                                                                        ()}},
                                                                              :Integer
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :integer-value?
                                                                              ()}},
                                                    :integer-binop
                                                    #:masr.specs{:integer-binop-enum
                                                                 "Sub",
                                                                 :term
                                                                 :masr.specs/integer-binop},
                                                    :integer-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/IntegerBinOp,
                                                                              :integer-left
                                                                              "Var_45906",
                                                                              :integer-binop
                                                                              #:masr.specs{:integer-binop-enum
                                                                                           "Mul",
                                                                                           :term
                                                                                           :masr.specs/integer-binop},
                                                                              :integer-right
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        16,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}},
                                                                              :Integer
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :integer-value?
                                                                              ()}},
                                                    :Integer
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Integer,
                                                                              :integer-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :integer-value?
                                                    ()}},
                          :overloaded ()}}

