(ns masr.resources.-test_numpy_03-6dd742e.Assignment.Assignment_47637)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_45888",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/FunctionCall,
                                                    :symbol-ref
                                                    #:masr.specs{:identifier
                                                                 "_lpython_floordiv__AT____lpython_overloaded_4___lpython_floordiv",
                                                                 :symtab-id
                                                                 201},
                                                    :orig-symref
                                                    #:masr.specs{:identifier
                                                                 "_lpython_floordiv",
                                                                 :symtab-id
                                                                 201},
                                                    :call-args
                                                    [[#:masr.specs{:term
                                                                   :masr.specs/expr,
                                                                   :asr-expr-head
                                                                   #:masr.specs{:expr-head
                                                                                :masr.specs/IntegerBinOp,
                                                                                :integer-left
                                                                                "Var_45891",
                                                                                :integer-binop
                                                                                #:masr.specs{:integer-binop-enum
                                                                                             "Sub",
                                                                                             :term
                                                                                             :masr.specs/integer-binop},
                                                                                :integer-right
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/IntegerBinOp,
                                                                                                          :integer-left
                                                                                                          "Var_45894",
                                                                                                          :integer-binop
                                                                                                          #:masr.specs{:integer-binop-enum
                                                                                                                       "Mul",
                                                                                                                       :term
                                                                                                                       :masr.specs/integer-binop},
                                                                                                          :integer-right
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:Integer
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Integer,
                                                                                                                                                              :integer-kind
                                                                                                                                                              4,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :int
                                                                                                                                    256,
                                                                                                                                    :expr-head
                                                                                                                                    :masr.specs/IntegerConstant}},
                                                                                                          :Integer
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Integer,
                                                                                                                                    :integer-kind
                                                                                                                                    4,
                                                                                                                                    :dimension*
                                                                                                                                    []}},
                                                                                                          :integer-value?
                                                                                                          ()}},
                                                                                :Integer
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/ttype,
                                                                                             :asr-ttype-head
                                                                                             #:masr.specs{:ttype-head
                                                                                                          :masr.specs/Integer,
                                                                                                          :integer-kind
                                                                                                          4,
                                                                                                          :dimension*
                                                                                                          []}},
                                                                                :integer-value?
                                                                                ()}}]
                                                     [#:masr.specs{:term
                                                                   :masr.specs/expr,
                                                                   :asr-expr-head
                                                                   #:masr.specs{:Integer
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/ttype,
                                                                                             :asr-ttype-head
                                                                                             #:masr.specs{:ttype-head
                                                                                                          :masr.specs/Integer,
                                                                                                          :integer-kind
                                                                                                          4,
                                                                                                          :dimension*
                                                                                                          []}},
                                                                                :int
                                                                                16,
                                                                                :expr-head
                                                                                :masr.specs/IntegerConstant}}]],
                                                    :return-type
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Integer,
                                                                              :integer-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :value? (),
                                                    :dt? ()}},
                          :overloaded ()}}

