(ns masr.resources.-test_numpy_03-6dd742e.Assignment.Assignment_47634)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_45882",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/Cast,
                                                    :arg
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/Cast,
                                                                              :arg
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/RealBinOp,
                                                                                                        :real-left
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/expr,
                                                                                                                     :asr-expr-head
                                                                                                                     #:masr.specs{:expr-head
                                                                                                                                  :masr.specs/Cast,
                                                                                                                                  :arg
                                                                                                                                  "Var_45885",
                                                                                                                                  :cast-kind
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/cast-kind,
                                                                                                                                               :cast-kind-enum
                                                                                                                                               "IntegerToReal"},
                                                                                                                                  :ttype
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/ttype,
                                                                                                                                               :asr-ttype-head
                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                            :masr.specs/Real,
                                                                                                                                                            :real-kind
                                                                                                                                                            8,
                                                                                                                                                            :dimension*
                                                                                                                                                            []}},
                                                                                                                                  :value?
                                                                                                                                  ()}},
                                                                                                        :real-binop
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/real-binop,
                                                                                                                     :real-binop-enum
                                                                                                                     "RDiv"},
                                                                                                        :real-right
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/expr,
                                                                                                                     :asr-expr-head
                                                                                                                     #:masr.specs{:expr-head
                                                                                                                                  :masr.specs/Cast,
                                                                                                                                  :arg
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/expr,
                                                                                                                                               :asr-expr-head
                                                                                                                                               #:masr.specs{:Integer
                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                         :masr.specs/ttype,
                                                                                                                                                                         :asr-ttype-head
                                                                                                                                                                         #:masr.specs{:ttype-head
                                                                                                                                                                                      :masr.specs/Integer,
                                                                                                                                                                                      :integer-kind
                                                                                                                                                                                      4,
                                                                                                                                                                                      :dimension*
                                                                                                                                                                                      []}},
                                                                                                                                                            :int
                                                                                                                                                            256,
                                                                                                                                                            :expr-head
                                                                                                                                                            :masr.specs/IntegerConstant}},
                                                                                                                                  :cast-kind
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/cast-kind,
                                                                                                                                               :cast-kind-enum
                                                                                                                                               "IntegerToReal"},
                                                                                                                                  :ttype
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/ttype,
                                                                                                                                               :asr-ttype-head
                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                            :masr.specs/Real,
                                                                                                                                                            :real-kind
                                                                                                                                                            8,
                                                                                                                                                            :dimension*
                                                                                                                                                            []}},
                                                                                                                                  :value?
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/expr,
                                                                                                                                               :asr-expr-head
                                                                                                                                               #:masr.specs{:float
                                                                                                                                                            256.0,
                                                                                                                                                            :expr-head
                                                                                                                                                            :masr.specs/RealConstant,
                                                                                                                                                            :Real
                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                         :masr.specs/ttype,
                                                                                                                                                                         :asr-ttype-head
                                                                                                                                                                         #:masr.specs{:ttype-head
                                                                                                                                                                                      :masr.specs/Real,
                                                                                                                                                                                      :real-kind
                                                                                                                                                                                      8,
                                                                                                                                                                                      :dimension*
                                                                                                                                                                                      []}}}}}},
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :real-value?
                                                                                                        ()}},
                                                                              :cast-kind
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/cast-kind,
                                                                                           :cast-kind-enum
                                                                                           "RealToInteger"},
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        8,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              ()}},
                                                    :cast-kind
                                                    #:masr.specs{:term
                                                                 :masr.specs/cast-kind,
                                                                 :cast-kind-enum
                                                                 "IntegerToInteger"},
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Integer,
                                                                              :integer-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :value? ()}},
                          :overloaded ()}}

