sed -f fix-show-asr.sed < ./stdouts/asr-array_01_decl-f955627.stdout > ./stdouts/asr-array_01_decl-f955627.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-array_02_decl-8860c8a.stdout > ./stdouts/asr-array_02_decl-8860c8a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-assert1-a8db80c.stdout > ./stdouts/asr-assert1-a8db80c.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-assign1-ec7ab8d.stdout > ./stdouts/asr-assign1-ec7ab8d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-assign2-4778d3a.stdout > ./stdouts/asr-assign2-4778d3a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-bindc_01-edd8cc4.stdout > ./stdouts/asr-bindc_01-edd8cc4.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-bindc_02-8c7fec3.stdout > ./stdouts/asr-bindc_02-8c7fec3.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-c_interop1-c0a6335.stdout > ./stdouts/asr-c_interop1-c0a6335.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-callback_01-64f7a94.stdout > ./stdouts/asr-callback_01-64f7a94.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-cast-d93d15f.stdout > ./stdouts/asr-cast-d93d15f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-complex1-7ce1c89.stdout > ./stdouts/asr-complex1-7ce1c89.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-constants1-20d32ff.stdout > ./stdouts/asr-constants1-20d32ff.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-dictionary1-789a50b.stdout > ./stdouts/asr-dictionary1-789a50b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-doconcurrentloop_01-7b9a7d3.stdout > ./stdouts/asr-doconcurrentloop_01-7b9a7d3.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-elemental_01-b6a1371.stdout > ./stdouts/asr-elemental_01-b6a1371.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr1-dde511e.stdout > ./stdouts/asr-expr1-dde511e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr10-31c163f.stdout > ./stdouts/asr-expr10-31c163f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr11-1134d3f.stdout > ./stdouts/asr-expr11-1134d3f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr12-2a30333.stdout > ./stdouts/asr-expr12-2a30333.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr13-10040d8.stdout > ./stdouts/asr-expr13-10040d8.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr2-5311701.stdout > ./stdouts/asr-expr2-5311701.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr4-cf512ef.stdout > ./stdouts/asr-expr4-cf512ef.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr5-375548a.stdout > ./stdouts/asr-expr5-375548a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr6-bfb3384.stdout > ./stdouts/asr-expr6-bfb3384.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr7-2ef3822.stdout > ./stdouts/asr-expr7-2ef3822.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr8-2a4630a.stdout > ./stdouts/asr-expr8-2a4630a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr9-c6fe691.stdout > ./stdouts/asr-expr9-c6fe691.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_01-03055c0.stdout > ./stdouts/asr-expr_01-03055c0.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_01-eafd41c.stdout > ./stdouts/asr-expr_01-eafd41c.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_05-45e5844.stdout > ./stdouts/asr-expr_05-45e5844.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_07-ccf2455.stdout > ./stdouts/asr-expr_07-ccf2455.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_09-0e8c1e6.stdout > ./stdouts/asr-expr_09-0e8c1e6.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_10-e2e0267.stdout > ./stdouts/asr-expr_10-e2e0267.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_12-7aa0c4c.stdout > ./stdouts/asr-expr_12-7aa0c4c.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-expr_14-6023c49.stdout > ./stdouts/asr-expr_14-6023c49.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-func_inline_01-56dbc9a.stdout > ./stdouts/asr-func_inline_01-56dbc9a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-generics_01-4ff9de7.stdout > ./stdouts/asr-generics_01-4ff9de7.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-generics_02-79b33a1.stdout > ./stdouts/asr-generics_02-79b33a1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-generics_array_01-8e0b4d1.stdout > ./stdouts/asr-generics_array_01-8e0b4d1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-generics_array_02-e149533.stdout > ./stdouts/asr-generics_array_02-e149533.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-generics_array_03-a1b8457.stdout > ./stdouts/asr-generics_array_03-a1b8457.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-generics_list_01-4ec4007.stdout > ./stdouts/asr-generics_list_01-4ec4007.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-global_scope1-b335bb9.stdout > ./stdouts/asr-global_scope1-b335bb9.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-global_syms_01-12ee218.stdout > ./stdouts/asr-global_syms_01-12ee218.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-list1-f15817d.stdout > ./stdouts/asr-list1-f15817d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-loop1-ce84aac.stdout > ./stdouts/asr-loop1-ce84aac.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-loop2-5e07e8f.stdout > ./stdouts/asr-loop2-5e07e8f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-loop3-e2afee9.stdout > ./stdouts/asr-loop3-e2afee9.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-loop4-b39f53b.stdout > ./stdouts/asr-loop4-b39f53b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-modules_02-5371fe0.stdout > ./stdouts/asr-modules_02-5371fe0.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-print_02-f237d46.stdout > ./stdouts/asr-print_02-f237d46.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-set1-7de4081.stdout > ./stdouts/asr-set1-7de4081.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-structs_01-c473a5f.stdout > ./stdouts/asr-structs_01-c473a5f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-structs_02-a0958ac.stdout > ./stdouts/asr-structs_02-a0958ac.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-structs_03-14c22b7.stdout > ./stdouts/asr-structs_03-14c22b7.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-structs_04-7e4824e.stdout > ./stdouts/asr-structs_04-7e4824e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-structs_05-2ccee30.stdout > ./stdouts/asr-structs_05-2ccee30.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-subscript1-22a7138.stdout > ./stdouts/asr-subscript1-22a7138.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_bool_binop-3075d22.stdout > ./stdouts/asr-test_bool_binop-3075d22.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin-4f04bbc.stdout > ./stdouts/asr-test_builtin-4f04bbc.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_abs-06a7e49.stdout > ./stdouts/asr-test_builtin_abs-06a7e49.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_bin-0ca34fe.stdout > ./stdouts/asr-test_builtin_bin-0ca34fe.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_bool-fe3fe33.stdout > ./stdouts/asr-test_builtin_bool-fe3fe33.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_float-97f9316.stdout > ./stdouts/asr-test_builtin_float-97f9316.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_hex-d4abc3e.stdout > ./stdouts/asr-test_builtin_hex-d4abc3e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_int-990d1de.stdout > ./stdouts/asr-test_builtin_int-990d1de.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_len-922cf65.stdout > ./stdouts/asr-test_builtin_len-922cf65.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_oct-490a98b.stdout > ./stdouts/asr-test_builtin_oct-490a98b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_pow-cea529e.stdout > ./stdouts/asr-test_builtin_pow-cea529e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_round-cca5cba.stdout > ./stdouts/asr-test_builtin_round-cca5cba.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_builtin_str-fcdedc2.stdout > ./stdouts/asr-test_builtin_str-fcdedc2.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_c_interop_01-8bee4ec.stdout > ./stdouts/asr-test_c_interop_01-8bee4ec.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_complex_01-c199562.stdout > ./stdouts/asr-test_complex_01-c199562.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_complex_02-6516823.stdout > ./stdouts/asr-test_complex_02-6516823.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_end_sep_keywords-49ea13f.stdout > ./stdouts/asr-test_end_sep_keywords-49ea13f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_integer_bitnot-0d0eafa.stdout > ./stdouts/asr-test_integer_bitnot-0d0eafa.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_max_min-e73decc.stdout > ./stdouts/asr-test_max_min-e73decc.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_numpy_03-6dd742e.stdout > ./stdouts/asr-test_numpy_03-6dd742e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_numpy_04-3376b7a.stdout > ./stdouts/asr-test_numpy_04-3376b7a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-test_pow-6f6a69d.stdout > ./stdouts/asr-test_pow-6f6a69d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-tuple1-ce358d9.stdout > ./stdouts/asr-tuple1-ce358d9.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/asr-vec_01-9b22f33.stdout > ./stdouts/asr-vec_01-9b22f33.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-assert1-ca86e1f.stdout > ./stdouts/ast-assert1-ca86e1f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-assign1-f667542.stdout > ./stdouts/ast-assign1-f667542.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-complex1-b52cd7b.stdout > ./stdouts/ast-complex1-b52cd7b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-constants1-66d568d.stdout > ./stdouts/ast-constants1-66d568d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-dictionary1-817b071.stdout > ./stdouts/ast-dictionary1-817b071.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-doconcurrentloop_01-5646034.stdout > ./stdouts/ast-doconcurrentloop_01-5646034.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-ellipsis1-dcbe16f.stdout > ./stdouts/ast-ellipsis1-dcbe16f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr1-20cdacc.stdout > ./stdouts/ast-expr1-20cdacc.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr10-49c656f.stdout > ./stdouts/ast-expr10-49c656f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr11-df775f8.stdout > ./stdouts/ast-expr11-df775f8.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr12-49f1f8d.stdout > ./stdouts/ast-expr12-49f1f8d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr13-b25242b.stdout > ./stdouts/ast-expr13-b25242b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr2-58df65e.stdout > ./stdouts/ast-expr2-58df65e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr4-78d463e.stdout > ./stdouts/ast-expr4-78d463e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr5-5e64a6e.stdout > ./stdouts/ast-expr5-5e64a6e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr6-9ba0998.stdout > ./stdouts/ast-expr6-9ba0998.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr7-bf4cb65.stdout > ./stdouts/ast-expr7-bf4cb65.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr8-beffee3.stdout > ./stdouts/ast-expr8-beffee3.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr9-187e786.stdout > ./stdouts/ast-expr9-187e786.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-expr_01-2d63276.stdout > ./stdouts/ast-expr_01-2d63276.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-global1-36fd19b.stdout > ./stdouts/ast-global1-36fd19b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-global_scope1-7809fe0.stdout > ./stdouts/ast-global_scope1-7809fe0.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-list1-2e4b88a.stdout > ./stdouts/ast-list1-2e4b88a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-loop1-d1c242e.stdout > ./stdouts/ast-loop1-d1c242e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-loop2-44a8219.stdout > ./stdouts/ast-loop2-44a8219.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-loop3-c545eab.stdout > ./stdouts/ast-loop3-c545eab.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-set1-8938049.stdout > ./stdouts/ast-set1-8938049.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-subscript1-76dcb5a.stdout > ./stdouts/ast-subscript1-76dcb5a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast-tuple1-0b7b893.stdout > ./stdouts/ast-tuple1-0b7b893.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-async1-3f88bf1.stdout > ./stdouts/ast_new-async1-3f88bf1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-boolOp1-6a81afc.stdout > ./stdouts/ast_new-boolOp1-6a81afc.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-class_def1-9fd9de1.stdout > ./stdouts/ast_new-class_def1-9fd9de1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-class_def2-505b454.stdout > ./stdouts/ast_new-class_def2-505b454.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-comment2-08e9f9a.stdout > ./stdouts/ast_new-comment2-08e9f9a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-comprehension1-575f5b3.stdout > ./stdouts/ast_new-comprehension1-575f5b3.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-conditional_expr1-b290d84.stdout > ./stdouts/ast_new-conditional_expr1-b290d84.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-dictionary1-a0c7807.stdout > ./stdouts/ast_new-dictionary1-a0c7807.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-ellipsis2-227f104.stdout > ./stdouts/ast_new-ellipsis2-227f104.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-for1-0494920.stdout > ./stdouts/ast_new-for1-0494920.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-for2-574cea6.stdout > ./stdouts/ast_new-for2-574cea6.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-function_def1-ca8dc19.stdout > ./stdouts/ast_new-function_def1-ca8dc19.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-function_def2-cead6f1.stdout > ./stdouts/ast_new-function_def2-cead6f1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-function_def3-a3f4dcf.stdout > ./stdouts/ast_new-function_def3-a3f4dcf.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-global1-4288396.stdout > ./stdouts/ast_new-global1-4288396.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-if1-e6432ed.stdout > ./stdouts/ast_new-if1-e6432ed.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-if2-33fa625.stdout > ./stdouts/ast_new-if2-33fa625.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-import1-6a0330c.stdout > ./stdouts/ast_new-import1-6a0330c.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-lambda1-58822d0.stdout > ./stdouts/ast_new-lambda1-58822d0.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-lambda2-d6a1f95.stdout > ./stdouts/ast_new-lambda2-d6a1f95.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-match_stmt1-9f49edb.stdout > ./stdouts/ast_new-match_stmt1-9f49edb.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-slice1-0471787.stdout > ./stdouts/ast_new-slice1-0471787.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-statements1-1685ab2.stdout > ./stdouts/ast_new-statements1-1685ab2.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-statements2-d9ec152.stdout > ./stdouts/ast_new-statements2-d9ec152.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-string1-f14340e.stdout > ./stdouts/ast_new-string1-f14340e.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-string2-b6abe54.stdout > ./stdouts/ast_new-string2-b6abe54.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-try1-be44da5.stdout > ./stdouts/ast_new-try1-be44da5.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-tuple1-3e447de.stdout > ./stdouts/ast_new-tuple1-3e447de.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-type_comment1-a1dfe37.stdout > ./stdouts/ast_new-type_comment1-a1dfe37.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-unicode-1c0cbec.stdout > ./stdouts/ast_new-unicode-1c0cbec.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-while1-1c5ee87.stdout > ./stdouts/ast_new-while1-1c5ee87.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-with1-cf2a022.stdout > ./stdouts/ast_new-with1-cf2a022.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/ast_new-yield-b585d08.stdout > ./stdouts/ast_new-yield-b585d08.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-c_interop1-e215531.stdout > ./stdouts/c-c_interop1-e215531.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-expr7-bb2692a.stdout > ./stdouts/c-expr7-bb2692a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-expr_01-28f449f.stdout > ./stdouts/c-expr_01-28f449f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-expr_11-c452314.stdout > ./stdouts/c-expr_11-c452314.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-expr_12-93c7780.stdout > ./stdouts/c-expr_12-93c7780.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-func_static_01-fc146ec.stdout > ./stdouts/c-func_static_01-fc146ec.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-import_order_01-3ebf3c3.stdout > ./stdouts/c-import_order_01-3ebf3c3.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-loop1-3e341c7.stdout > ./stdouts/c-loop1-3e341c7.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-loop2-ce7de51.stdout > ./stdouts/c-loop2-ce7de51.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-loop4-eec10d3.stdout > ./stdouts/c-loop4-eec10d3.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-print_01-4d44628.stdout > ./stdouts/c-print_01-4d44628.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-test_import_02-d2c54c4.stdout > ./stdouts/c-test_import_02-d2c54c4.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-test_issue_518-fbbd299.stdout > ./stdouts/c-test_issue_518-fbbd299.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/c-variable_decl_03-fa1823b.stdout > ./stdouts/c-variable_decl_03-fa1823b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-assert1-ba60925.stdout > ./stdouts/cpp-assert1-ba60925.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-doconcurrentloop_01-4e9f274.stdout > ./stdouts/cpp-doconcurrentloop_01-4e9f274.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr12-fd2ea87.stdout > ./stdouts/cpp-expr12-fd2ea87.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr15-1661c0d.stdout > ./stdouts/cpp-expr15-1661c0d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr2-09c05ad.stdout > ./stdouts/cpp-expr2-09c05ad.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr5-1de0e30.stdout > ./stdouts/cpp-expr5-1de0e30.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr6-f337f4f.stdout > ./stdouts/cpp-expr6-f337f4f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr7-529bd53.stdout > ./stdouts/cpp-expr7-529bd53.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr8-704cece.stdout > ./stdouts/cpp-expr8-704cece.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr9-48868e9.stdout > ./stdouts/cpp-expr9-48868e9.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-expr_11-422c839.stdout > ./stdouts/cpp-expr_11-422c839.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-loop1-0a8cf3b.stdout > ./stdouts/cpp-loop1-0a8cf3b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-loop3-6020091.stdout > ./stdouts/cpp-loop3-6020091.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-loop4-cdb2174.stdout > ./stdouts/cpp-loop4-cdb2174.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-print_01-026ef17.stdout > ./stdouts/cpp-print_01-026ef17.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-test_builtin_pow-56b3f92.stdout > ./stdouts/cpp-test_builtin_pow-56b3f92.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/cpp-test_integer_bitnot-20195fd.stdout > ./stdouts/cpp-test_integer_bitnot-20195fd.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-assert1-8df4f31.stdout > ./stdouts/llvm-assert1-8df4f31.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-bindc_01-c984f09.stdout > ./stdouts/llvm-bindc_01-c984f09.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-bool1-af4376b.stdout > ./stdouts/llvm-bool1-af4376b.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-expr14-b96b5b1.stdout > ./stdouts/llvm-expr14-b96b5b1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-expr_01-54467c1.stdout > ./stdouts/llvm-expr_01-54467c1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-func_inline_01-2d4583a.stdout > ./stdouts/llvm-func_inline_01-2d4583a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-lpython1-23c5987.stdout > ./stdouts/llvm-lpython1-23c5987.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-print_04-443a8d8.stdout > ./stdouts/llvm-print_04-443a8d8.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-test_integer_bitnot-6894b6d.stdout > ./stdouts/llvm-test_integer_bitnot-6894b6d.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm-test_issue_518-cdb641a.stdout > ./stdouts/llvm-test_issue_518-cdb641a.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/llvm_dbg-expr_01-9fc5f30.stdout > ./stdouts/llvm_dbg-expr_01-9fc5f30.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/pass_inline_function_calls-func_inline_01-6cf8821.stdout > ./stdouts/pass_inline_function_calls-func_inline_01-6cf8821.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/pass_loop_vectorise-vec_01-fdf30b1.stdout > ./stdouts/pass_loop_vectorise-vec_01-fdf30b1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/pass_print_list_tuple-print_02-1bcc4ec.stdout > ./stdouts/pass_print_list_tuple-print_02-1bcc4ec.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/runtime-test_str_01-50bdf2f.stdout > ./stdouts/runtime-test_str_01-50bdf2f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/runtime-test_str_02-c38ba27.stdout > ./stdouts/runtime-test_str_02-c38ba27.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-comment1-2f8ab90.stdout > ./stdouts/tokens-comment1-2f8ab90.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-comment2-b289dad.stdout > ./stdouts/tokens-comment2-b289dad.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-docstring1-1355fbb.stdout > ./stdouts/tokens-docstring1-1355fbb.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-indent1-290e858.stdout > ./stdouts/tokens-indent1-290e858.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-indent2-e702789.stdout > ./stdouts/tokens-indent2-e702789.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-numbers1-589063f.stdout > ./stdouts/tokens-numbers1-589063f.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/tokens-symbols1-658c990.stdout > ./stdouts/tokens-symbols1-658c990.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/wat-bool1-234bcd1.stdout > ./stdouts/wat-bool1-234bcd1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/wat-expr14-5e0cb96.stdout > ./stdouts/wat-expr14-5e0cb96.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/wat-expr2-8b17723.stdout > ./stdouts/wat-expr2-8b17723.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/wat-expr9-f73afd1.stdout > ./stdouts/wat-expr9-f73afd1.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/wat-loop1-e0046d4.stdout > ./stdouts/wat-loop1-e0046d4.stdout.clj
sed -f fix-show-asr.sed < ./stdouts/wat-print_str-385e953.stdout > ./stdouts/wat-print_str-385e953.stdout.clj
