(ns masr.resources.-vec_01-9b22f33.SymbolTable.SymbolTable_71277)


#:masr.specs{:term :masr.specs/SymbolTable,
             :symtab-id 1,
             :hash-map
             {:_global_symbols
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/Module,
                                        :SymbolTable
                                        #:masr.specs{:term
                                                     :masr.specs/SymbolTable,
                                                     :symtab-id 191,
                                                     :hash-map
                                                     {:_lpython_main_program
                                                      "Function_71049",
                                                      :loop_vec
                                                      "Function_71052"}},
                                        :modulenym "_global_symbols",
                                        :dependencies [],
                                        :loaded-from-mod false,
                                        :intrinsic false}},
              :lpython_builtin
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/IntrinsicModule,
                                        :modulenym "lpython_builtin"}},
              :main_program
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/Program,
                                        :SymbolTable
                                        #:masr.specs{:term
                                                     :masr.specs/SymbolTable,
                                                     :symtab-id 189,
                                                     :hash-map
                                                     {:_lpython_main_program
                                                      "ExternalSymbol_71019"}},
                                        :prognym "main_program",
                                        :dependencies
                                        ["_global_symbols"],
                                        :body
                                        ["SubroutineCall_71046"]}},
              :numpy
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/Module,
                                        :SymbolTable
                                        #:masr.specs{:term
                                                     :masr.specs/SymbolTable,
                                                     :symtab-id 3,
                                                     :hash-map
                                                     {:_lfortran_dlog
                                                      "Function_71055",
                                                      :__lpython_overloaded_1__sinh
                                                      "Function_71058",
                                                      :__lpython_overloaded_0__degrees
                                                      "Function_71061",
                                                      :_lfortran_dacos
                                                      "Function_71064",
                                                      :pi_64
                                                      "Variable_70179",
                                                      :ceil
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "ceil",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__ceil",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__ceil",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arcsinh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arcsinh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arcsinh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arcsinh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__arcsinh
                                                      "Function_71067",
                                                      :_lfortran_datan
                                                      "Function_71070",
                                                      :__lpython_overloaded_0__ceil
                                                      "Function_71073",
                                                      :_lfortran_stan
                                                      "Function_71076",
                                                      :_lfortran_satan
                                                      "Function_71079",
                                                      :__lpython_overloaded_0__arccos
                                                      "Function_71082",
                                                      :_lfortran_dtan
                                                      "Function_71085",
                                                      :cos
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "cos",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__cos",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__cos",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :log10
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "log10",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__log10",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__log10",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__sin
                                                      "Function_71088",
                                                      :_lfortran_ssinh
                                                      "Function_71091",
                                                      :__lpython_overloaded_0__log10
                                                      "Function_71094",
                                                      :__lpython_overloaded_0__arccosh
                                                      "Function_71097",
                                                      :_lfortran_sexp
                                                      "Function_71100",
                                                      :__lpython_overloaded_1__cos
                                                      "Function_71103",
                                                      :tan
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "tan",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__tan",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__tan",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_0__log2
                                                      "Function_71106",
                                                      :__lpython_overloaded_0__cosh
                                                      "Function_71109",
                                                      :pi_32
                                                      "Variable_70275",
                                                      :__lpython_overloaded_1__log
                                                      "Function_71112",
                                                      :arccosh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arccosh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arccosh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arccosh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_dcosh
                                                      "Function_71115",
                                                      :arcsin
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arcsin",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arcsin",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arcsin",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :sqrt
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "sqrt",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__sqrt",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__sqrt",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_scos
                                                      "Function_71118",
                                                      :_lfortran_satanh
                                                      "Function_71121",
                                                      :_lfortran_sasinh
                                                      "Function_71124",
                                                      :__lpython_overloaded_1__floor
                                                      "Function_71127",
                                                      :mod
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "mod",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__mod",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__mod",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_slog10
                                                      "Function_71130",
                                                      :__lpython_overloaded_0__log
                                                      "Function_71133",
                                                      :__lpython_overloaded_1__tan
                                                      "Function_71136",
                                                      :exp
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "exp",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__exp",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__exp",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :cosh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "cosh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__cosh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__cosh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__tanh
                                                      "Function_71139",
                                                      :__lpython_overloaded_0__arctanh
                                                      "Function_71142",
                                                      :__lpython_overloaded_1__degrees
                                                      "Function_71145",
                                                      :_lfortran_datanh
                                                      "Function_71148",
                                                      :_lfortran_slog
                                                      "Function_71151",
                                                      :__lpython_overloaded_0__sqrt
                                                      "Function_71154",
                                                      :log2
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "log2",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__log2",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__log2",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__arctan
                                                      "Function_71157",
                                                      :__lpython_overloaded_0__cos
                                                      "Function_71160",
                                                      :__lpython_overloaded_0__tan
                                                      "Function_71163",
                                                      :__lpython_overloaded_1__arcsin
                                                      "Function_71166",
                                                      :__lpython_overloaded_0__radians
                                                      "Function_71169",
                                                      :_lfortran_dcos
                                                      "Function_71172",
                                                      :__lpython_overloaded_0__arcsinh
                                                      "Function_71175",
                                                      :__lpython_overloaded_1__log2
                                                      "Function_71178",
                                                      :__lpython_overloaded_1__sqrt
                                                      "Function_71181",
                                                      :_lfortran_dacosh
                                                      "Function_71184",
                                                      :_lfortran_dasin
                                                      "Function_71187",
                                                      :__lpython_overloaded_0__arctan
                                                      "Function_71190",
                                                      :sinh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "sinh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__sinh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__sinh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arctanh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arctanh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arctanh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arctanh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_sasin
                                                      "Function_71193",
                                                      :__lpython_overloaded_1__ceil
                                                      "Function_71196",
                                                      :_lfortran_dasinh
                                                      "Function_71199",
                                                      :__lpython_overloaded_1__cosh
                                                      "Function_71202",
                                                      :_lfortran_dsin
                                                      "Function_71205",
                                                      :_lfortran_dtanh
                                                      "Function_71208",
                                                      :_lfortran_sacos
                                                      "Function_71211",
                                                      :__lpython_overloaded_0__sin
                                                      "Function_71214",
                                                      :sin
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "sin",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__sin",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__sin",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__arccos
                                                      "Function_71217",
                                                      :__lpython_overloaded_1__exp
                                                      "Function_71220",
                                                      :__lpython_overloaded_0__tanh
                                                      "Function_71223",
                                                      :_lfortran_dlog10
                                                      "Function_71226",
                                                      :_lfortran_stanh
                                                      "Function_71229",
                                                      :__lpython_overloaded_1__radians
                                                      "Function_71232",
                                                      :_lfortran_dexp
                                                      "Function_71235",
                                                      :__lpython_overloaded_1__mod
                                                      "Function_71238",
                                                      :__lpython_overloaded_0__arcsin
                                                      "Function_71241",
                                                      :_lfortran_ssin
                                                      "Function_71244",
                                                      :__lpython_overloaded_1__arccosh
                                                      "Function_71247",
                                                      :_lfortran_sacosh
                                                      "Function_71250",
                                                      :__lpython_overloaded_1__arctanh
                                                      "Function_71253",
                                                      :_lfortran_scosh
                                                      "Function_71256",
                                                      :__lpython_overloaded_0__exp
                                                      "Function_71259",
                                                      :radians
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "radians",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__radians",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__radians",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :degrees
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "degrees",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__degrees",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__degrees",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arctan
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arctan",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arctan",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arctan",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_0__sinh
                                                      "Function_71262",
                                                      :log
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "log",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__log",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__log",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :floor
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "floor",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__floor",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__floor",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arccos
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arccos",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arccos",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arccos",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :tanh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "tanh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__tanh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__tanh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_0__floor
                                                      "Function_71265",
                                                      :_lfortran_dsinh
                                                      "Function_71268",
                                                      :__lpython_overloaded_0__mod
                                                      "Function_71271",
                                                      :__lpython_overloaded_1__log10
                                                      "Function_71274"}},
                                        :modulenym "numpy",
                                        :dependencies
                                        ["lpython_builtin"],
                                        :loaded-from-mod false,
                                        :intrinsic false}}}}

