(ns masr.resources.-expr_07-ccf2455.Function.Function_19923)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_19878"
                           "Print_19899"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_19803",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "LogicalToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "True",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   4,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_19881"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         "Var_19809",
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "LogicalToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "False",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   5,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:Logical
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:logical-kind
                                                                                                                                                             4,
                                                                                                                                                             :ttype-head
                                                                                                                                                             :masr.specs/Logical,
                                                                                                                                                             :dimension*
                                                                                                                                                             []}},
                                                                                                                                   :expr-head
                                                                                                                                   :masr.specs/LogicalConstant,
                                                                                                                                   :bool
                                                                                                                                   true}},
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "LogicalToCharacter"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:expr-head
                                                                                                                                   :masr.specs/StringConstant,
                                                                                                                                   :string
                                                                                                                                   "True",
                                                                                                                                   :Character
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Character,
                                                                                                                                                             :character-kind
                                                                                                                                                             1,
                                                                                                                                                             :len
                                                                                                                                                             4,
                                                                                                                                                             :disposition
                                                                                                                                                             "compile-time-length",
                                                                                                                                                             :len-expr?
                                                                                                                                                             (),
                                                                                                                                                             :dimension*
                                                                                                                                                             []}}}}}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "True",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   4,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Logical
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:logical-kind
                                                                                                                                   4,
                                                                                                                                   :ttype-head
                                                                                                                                   :masr.specs/Logical,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :expr-head
                                                                                                         :masr.specs/LogicalConstant,
                                                                                                         :bool
                                                                                                         true}}}},
                                                     :message? ()}}],
                          :dependencies [],
                          :deterministic false,
                          :function-signature "FunctionType_19869",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 4,
                                       :hash-map
                                       {:var "Variable_19848"}},
                          :function-name "bool_to_str"}}

