(ns masr.resources.-test_numpy_03-6dd742e.DoLoop.DoLoop_47856)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/DoLoop,
                          :escape-target (),
                          :do-loop-head
                          #:masr.specs{:loop-v "Var_45708",
                                       :loop-start
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 0,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}},
                                       :loop-end
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:expr-head
                                                                 :masr.specs/IntegerBinOp,
                                                                 :integer-left
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           16,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}},
                                                                 :integer-binop
                                                                 #:masr.specs{:integer-binop-enum
                                                                              "Sub",
                                                                              :term
                                                                              :masr.specs/integer-binop},
                                                                 :integer-right
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           1,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}},
                                                                 :Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :integer-value?
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           15,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}}}},
                                       :loop-increment
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 1,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}}},
                          :body
                          [#:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/DoLoop,
                                                     :escape-target (),
                                                     :do-loop-head
                                                     #:masr.specs{:loop-v
                                                                  "Var_45711",
                                                                  :loop-start
                                                                  #:masr.specs{:term
                                                                               :masr.specs/expr,
                                                                               :asr-expr-head
                                                                               #:masr.specs{:Integer
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/ttype,
                                                                                                         :asr-ttype-head
                                                                                                         #:masr.specs{:ttype-head
                                                                                                                      :masr.specs/Integer,
                                                                                                                      :integer-kind
                                                                                                                      4,
                                                                                                                      :dimension*
                                                                                                                      []}},
                                                                                            :int
                                                                                            0,
                                                                                            :expr-head
                                                                                            :masr.specs/IntegerConstant}},
                                                                  :loop-end
                                                                  #:masr.specs{:term
                                                                               :masr.specs/expr,
                                                                               :asr-expr-head
                                                                               #:masr.specs{:expr-head
                                                                                            :masr.specs/IntegerBinOp,
                                                                                            :integer-left
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/expr,
                                                                                                         :asr-expr-head
                                                                                                         #:masr.specs{:Integer
                                                                                                                      #:masr.specs{:term
                                                                                                                                   :masr.specs/ttype,
                                                                                                                                   :asr-ttype-head
                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                :integer-kind
                                                                                                                                                4,
                                                                                                                                                :dimension*
                                                                                                                                                []}},
                                                                                                                      :int
                                                                                                                      16,
                                                                                                                      :expr-head
                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                            :integer-binop
                                                                                            #:masr.specs{:integer-binop-enum
                                                                                                         "Sub",
                                                                                                         :term
                                                                                                         :masr.specs/integer-binop},
                                                                                            :integer-right
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/expr,
                                                                                                         :asr-expr-head
                                                                                                         #:masr.specs{:Integer
                                                                                                                      #:masr.specs{:term
                                                                                                                                   :masr.specs/ttype,
                                                                                                                                   :asr-ttype-head
                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                :integer-kind
                                                                                                                                                4,
                                                                                                                                                :dimension*
                                                                                                                                                []}},
                                                                                                                      :int
                                                                                                                      1,
                                                                                                                      :expr-head
                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                            :Integer
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/ttype,
                                                                                                         :asr-ttype-head
                                                                                                         #:masr.specs{:ttype-head
                                                                                                                      :masr.specs/Integer,
                                                                                                                      :integer-kind
                                                                                                                      4,
                                                                                                                      :dimension*
                                                                                                                      []}},
                                                                                            :integer-value?
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/expr,
                                                                                                         :asr-expr-head
                                                                                                         #:masr.specs{:Integer
                                                                                                                      #:masr.specs{:term
                                                                                                                                   :masr.specs/ttype,
                                                                                                                                   :asr-ttype-head
                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                :integer-kind
                                                                                                                                                4,
                                                                                                                                                :dimension*
                                                                                                                                                []}},
                                                                                                                      :int
                                                                                                                      15,
                                                                                                                      :expr-head
                                                                                                                      :masr.specs/IntegerConstant}}}},
                                                                  :loop-increment
                                                                  #:masr.specs{:term
                                                                               :masr.specs/expr,
                                                                               :asr-expr-head
                                                                               #:masr.specs{:Integer
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/ttype,
                                                                                                         :asr-ttype-head
                                                                                                         #:masr.specs{:ttype-head
                                                                                                                      :masr.specs/Integer,
                                                                                                                      :integer-kind
                                                                                                                      4,
                                                                                                                      :dimension*
                                                                                                                      []}},
                                                                                            :int
                                                                                            1,
                                                                                            :expr-head
                                                                                            :masr.specs/IntegerConstant}}},
                                                     :body
                                                     [#:masr.specs{:term
                                                                   :masr.specs/stmt,
                                                                   :asr-stmt-head
                                                                   #:masr.specs{:stmt-head
                                                                                :masr.specs/DoLoop,
                                                                                :escape-target
                                                                                (),
                                                                                :do-loop-head
                                                                                #:masr.specs{:loop-v
                                                                                             "Var_45714",
                                                                                             :loop-start
                                                                                             #:masr.specs{:term
                                                                                                          :masr.specs/expr,
                                                                                                          :asr-expr-head
                                                                                                          #:masr.specs{:Integer
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/ttype,
                                                                                                                                    :asr-ttype-head
                                                                                                                                    #:masr.specs{:ttype-head
                                                                                                                                                 :masr.specs/Integer,
                                                                                                                                                 :integer-kind
                                                                                                                                                 4,
                                                                                                                                                 :dimension*
                                                                                                                                                 []}},
                                                                                                                       :int
                                                                                                                       0,
                                                                                                                       :expr-head
                                                                                                                       :masr.specs/IntegerConstant}},
                                                                                             :loop-end
                                                                                             #:masr.specs{:term
                                                                                                          :masr.specs/expr,
                                                                                                          :asr-expr-head
                                                                                                          #:masr.specs{:expr-head
                                                                                                                       :masr.specs/IntegerBinOp,
                                                                                                                       :integer-left
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/expr,
                                                                                                                                    :asr-expr-head
                                                                                                                                    #:masr.specs{:Integer
                                                                                                                                                 #:masr.specs{:term
                                                                                                                                                              :masr.specs/ttype,
                                                                                                                                                              :asr-ttype-head
                                                                                                                                                              #:masr.specs{:ttype-head
                                                                                                                                                                           :masr.specs/Integer,
                                                                                                                                                                           :integer-kind
                                                                                                                                                                           4,
                                                                                                                                                                           :dimension*
                                                                                                                                                                           []}},
                                                                                                                                                 :int
                                                                                                                                                 16,
                                                                                                                                                 :expr-head
                                                                                                                                                 :masr.specs/IntegerConstant}},
                                                                                                                       :integer-binop
                                                                                                                       #:masr.specs{:integer-binop-enum
                                                                                                                                    "Sub",
                                                                                                                                    :term
                                                                                                                                    :masr.specs/integer-binop},
                                                                                                                       :integer-right
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/expr,
                                                                                                                                    :asr-expr-head
                                                                                                                                    #:masr.specs{:Integer
                                                                                                                                                 #:masr.specs{:term
                                                                                                                                                              :masr.specs/ttype,
                                                                                                                                                              :asr-ttype-head
                                                                                                                                                              #:masr.specs{:ttype-head
                                                                                                                                                                           :masr.specs/Integer,
                                                                                                                                                                           :integer-kind
                                                                                                                                                                           4,
                                                                                                                                                                           :dimension*
                                                                                                                                                                           []}},
                                                                                                                                                 :int
                                                                                                                                                 1,
                                                                                                                                                 :expr-head
                                                                                                                                                 :masr.specs/IntegerConstant}},
                                                                                                                       :Integer
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/ttype,
                                                                                                                                    :asr-ttype-head
                                                                                                                                    #:masr.specs{:ttype-head
                                                                                                                                                 :masr.specs/Integer,
                                                                                                                                                 :integer-kind
                                                                                                                                                 4,
                                                                                                                                                 :dimension*
                                                                                                                                                 []}},
                                                                                                                       :integer-value?
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/expr,
                                                                                                                                    :asr-expr-head
                                                                                                                                    #:masr.specs{:Integer
                                                                                                                                                 #:masr.specs{:term
                                                                                                                                                              :masr.specs/ttype,
                                                                                                                                                              :asr-ttype-head
                                                                                                                                                              #:masr.specs{:ttype-head
                                                                                                                                                                           :masr.specs/Integer,
                                                                                                                                                                           :integer-kind
                                                                                                                                                                           4,
                                                                                                                                                                           :dimension*
                                                                                                                                                                           []}},
                                                                                                                                                 :int
                                                                                                                                                 15,
                                                                                                                                                 :expr-head
                                                                                                                                                 :masr.specs/IntegerConstant}}}},
                                                                                             :loop-increment
                                                                                             #:masr.specs{:term
                                                                                                          :masr.specs/expr,
                                                                                                          :asr-expr-head
                                                                                                          #:masr.specs{:Integer
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/ttype,
                                                                                                                                    :asr-ttype-head
                                                                                                                                    #:masr.specs{:ttype-head
                                                                                                                                                 :masr.specs/Integer,
                                                                                                                                                 :integer-kind
                                                                                                                                                 4,
                                                                                                                                                 :dimension*
                                                                                                                                                 []}},
                                                                                                                       :int
                                                                                                                       1,
                                                                                                                       :expr-head
                                                                                                                       :masr.specs/IntegerConstant}}},
                                                                                :body
                                                                                [#:masr.specs{:term
                                                                                              :masr.specs/stmt,
                                                                                              :asr-stmt-head
                                                                                              #:masr.specs{:stmt-head
                                                                                                           :masr.specs/Assert,
                                                                                                           :test-expr
                                                                                                           #:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:expr-head
                                                                                                                                     :masr.specs/RealCompare,
                                                                                                                                     :real-left
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/expr,
                                                                                                                                                  :asr-expr-head
                                                                                                                                                  #:masr.specs{:expr-head
                                                                                                                                                               :masr.specs/IntrinsicFunction,
                                                                                                                                                               :intrinsic-ident
                                                                                                                                                               "Abs",
                                                                                                                                                               :expr*
                                                                                                                                                               [#:masr.specs{:term
                                                                                                                                                                             :masr.specs/expr,
                                                                                                                                                                             :asr-expr-head
                                                                                                                                                                             #:masr.specs{:expr-head
                                                                                                                                                                                          :masr.specs/RealBinOp,
                                                                                                                                                                                          :real-left
                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                       :masr.specs/expr,
                                                                                                                                                                                                       :asr-expr-head
                                                                                                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                                                                                                    :real-left
                                                                                                                                                                                                                    #:masr.specs{:term
                                                                                                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                                                                                                 :asr-expr-head
                                                                                                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                                                                                                              :masr.specs/ArrayItem,
                                                                                                                                                                                                                                              :array-expr
                                                                                                                                                                                                                                              "Var_45717",
                                                                                                                                                                                                                                              :array-index*
                                                                                                                                                                                                                                              [#:masr.specs{:array-index-start?
                                                                                                                                                                                                                                                            (),
                                                                                                                                                                                                                                                            :array-index-end?
                                                                                                                                                                                                                                                            "Var_45720",
                                                                                                                                                                                                                                                            :array-index-increment?
                                                                                                                                                                                                                                                            ()}
                                                                                                                                                                                                                                               #:masr.specs{:array-index-start?
                                                                                                                                                                                                                                                            (),
                                                                                                                                                                                                                                                            :array-index-end?
                                                                                                                                                                                                                                                            "Var_45723",
                                                                                                                                                                                                                                                            :array-index-increment?
                                                                                                                                                                                                                                                            ()}
                                                                                                                                                                                                                                               #:masr.specs{:array-index-start?
                                                                                                                                                                                                                                                            (),
                                                                                                                                                                                                                                                            :array-index-end?
                                                                                                                                                                                                                                                            "Var_45726",
                                                                                                                                                                                                                                                            :array-index-increment?
                                                                                                                                                                                                                                                            ()}],
                                                                                                                                                                                                                                              :ttype
                                                                                                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                                                                                                        :real-kind
                                                                                                                                                                                                                                                                        8,
                                                                                                                                                                                                                                                                        :dimension*
                                                                                                                                                                                                                                                                        []}},
                                                                                                                                                                                                                                              :array-storage
                                                                                                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                                                                                                           :masr.specs/arraystorage,
                                                                                                                                                                                                                                                           :arraystorage-enum
                                                                                                                                                                                                                                                           "RowMajor"},
                                                                                                                                                                                                                                              :expr?
                                                                                                                                                                                                                                              ()}},
                                                                                                                                                                                                                    :real-binop
                                                                                                                                                                                                                    #:masr.specs{:term
                                                                                                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                                                                                                 :real-binop-enum
                                                                                                                                                                                                                                 "RSub"},
                                                                                                                                                                                                                    :real-right
                                                                                                                                                                                                                    #:masr.specs{:term
                                                                                                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                                                                                                 :asr-expr-head
                                                                                                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                                                                                                              :masr.specs/Cast,
                                                                                                                                                                                                                                              :arg
                                                                                                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                                                                                                           #:masr.specs{:expr-head
                                                                                                                                                                                                                                                                        :masr.specs/IntegerBinOp,
                                                                                                                                                                                                                                                                        :integer-left
                                                                                                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                                                                                                     :masr.specs/expr,
                                                                                                                                                                                                                                                                                     :asr-expr-head
                                                                                                                                                                                                                                                                                     #:masr.specs{:expr-head
                                                                                                                                                                                                                                                                                                  :masr.specs/IntegerBinOp,
                                                                                                                                                                                                                                                                                                  :integer-left
                                                                                                                                                                                                                                                                                                  "Var_45729",
                                                                                                                                                                                                                                                                                                  :integer-binop
                                                                                                                                                                                                                                                                                                  #:masr.specs{:integer-binop-enum
                                                                                                                                                                                                                                                                                                               "Add",
                                                                                                                                                                                                                                                                                                               :term
                                                                                                                                                                                                                                                                                                               :masr.specs/integer-binop},
                                                                                                                                                                                                                                                                                                  :integer-right
                                                                                                                                                                                                                                                                                                  "Var_45732",
                                                                                                                                                                                                                                                                                                  :Integer
                                                                                                                                                                                                                                                                                                  #:masr.specs{:term
                                                                                                                                                                                                                                                                                                               :masr.specs/ttype,
                                                                                                                                                                                                                                                                                                               :asr-ttype-head
                                                                                                                                                                                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                                                                            :masr.specs/Integer,
                                                                                                                                                                                                                                                                                                                            :integer-kind
                                                                                                                                                                                                                                                                                                                            4,
                                                                                                                                                                                                                                                                                                                            :dimension*
                                                                                                                                                                                                                                                                                                                            []}},
                                                                                                                                                                                                                                                                                                  :integer-value?
                                                                                                                                                                                                                                                                                                  ()}},
                                                                                                                                                                                                                                                                        :integer-binop
                                                                                                                                                                                                                                                                        #:masr.specs{:integer-binop-enum
                                                                                                                                                                                                                                                                                     "Add",
                                                                                                                                                                                                                                                                                     :term
                                                                                                                                                                                                                                                                                     :masr.specs/integer-binop},
                                                                                                                                                                                                                                                                        :integer-right
                                                                                                                                                                                                                                                                        "Var_45735",
                                                                                                                                                                                                                                                                        :Integer
                                                                                                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                                                                                                  []}},
                                                                                                                                                                                                                                                                        :integer-value?
                                                                                                                                                                                                                                                                        ()}},
                                                                                                                                                                                                                                              :cast-kind
                                                                                                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                                                                                                           :masr.specs/cast-kind,
                                                                                                                                                                                                                                                           :cast-kind-enum
                                                                                                                                                                                                                                                           "IntegerToReal"},
                                                                                                                                                                                                                                              :ttype
                                                                                                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                                                                                                        :real-kind
                                                                                                                                                                                                                                                                        8,
                                                                                                                                                                                                                                                                        :dimension*
                                                                                                                                                                                                                                                                        []}},
                                                                                                                                                                                                                                              :value?
                                                                                                                                                                                                                                              ()}},
                                                                                                                                                                                                                    :Real
                                                                                                                                                                                                                    #:masr.specs{:term
                                                                                                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                                                                                                 :asr-ttype-head
                                                                                                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                                                                                                              :real-kind
                                                                                                                                                                                                                                              8,
                                                                                                                                                                                                                                              :dimension*
                                                                                                                                                                                                                                              []}},
                                                                                                                                                                                                                    :real-value?
                                                                                                                                                                                                                    ()}},
                                                                                                                                                                                          :real-binop
                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                       :masr.specs/real-binop,
                                                                                                                                                                                                       :real-binop-enum
                                                                                                                                                                                                       "RSub"},
                                                                                                                                                                                          :real-right
                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                       :masr.specs/expr,
                                                                                                                                                                                                       :asr-expr-head
                                                                                                                                                                                                       #:masr.specs{:float
                                                                                                                                                                                                                    0.5,
                                                                                                                                                                                                                    :expr-head
                                                                                                                                                                                                                    :masr.specs/RealConstant,
                                                                                                                                                                                                                    :Real
                                                                                                                                                                                                                    #:masr.specs{:term
                                                                                                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                                                                                                 :asr-ttype-head
                                                                                                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                                                                                                              :real-kind
                                                                                                                                                                                                                                              8,
                                                                                                                                                                                                                                              :dimension*
                                                                                                                                                                                                                                              []}}}},
                                                                                                                                                                                          :Real
                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                       :masr.specs/ttype,
                                                                                                                                                                                                       :asr-ttype-head
                                                                                                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                                                                                                    :masr.specs/Real,
                                                                                                                                                                                                                    :real-kind
                                                                                                                                                                                                                    8,
                                                                                                                                                                                                                    :dimension*
                                                                                                                                                                                                                    []}},
                                                                                                                                                                                          :real-value?
                                                                                                                                                                                          ()}}],
                                                                                                                                                               :overload-id
                                                                                                                                                               0,
                                                                                                                                                               :return-type
                                                                                                                                                               #:masr.specs{:term
                                                                                                                                                                            :masr.specs/ttype,
                                                                                                                                                                            :asr-ttype-head
                                                                                                                                                                            #:masr.specs{:ttype-head
                                                                                                                                                                                         :masr.specs/Real,
                                                                                                                                                                                         :real-kind
                                                                                                                                                                                         8,
                                                                                                                                                                                         :dimension*
                                                                                                                                                                                         []}},
                                                                                                                                                               :value?
                                                                                                                                                               ()}},
                                                                                                                                     :real-cmpop
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/real-cmpop,
                                                                                                                                                  :real-cmpop-enum
                                                                                                                                                  "RLtE"},
                                                                                                                                     :real-right
                                                                                                                                     "Var_45738",
                                                                                                                                     :Logical
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:logical-kind
                                                                                                                                                               4,
                                                                                                                                                               :ttype-head
                                                                                                                                                               :masr.specs/Logical,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :logical-value?
                                                                                                                                     ()}},
                                                                                                           :message?
                                                                                                           ()}}]}}]}}]}}

