(ns masr.resources.-test_numpy_03-6dd742e.DoLoop.DoLoop_47868)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/DoLoop,
                          :escape-target (),
                          :do-loop-head
                          #:masr.specs{:loop-v "Var_45924",
                                       :loop-start
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 0,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}},
                                       :loop-end
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:expr-head
                                                                 :masr.specs/IntegerBinOp,
                                                                 :integer-left
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           16,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}},
                                                                 :integer-binop
                                                                 #:masr.specs{:integer-binop-enum
                                                                              "Sub",
                                                                              :term
                                                                              :masr.specs/integer-binop},
                                                                 :integer-right
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           1,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}},
                                                                 :Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :integer-value?
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           15,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}}}},
                                       :loop-increment
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 1,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}}},
                          :body
                          [#:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/DoLoop,
                                                     :escape-target (),
                                                     :do-loop-head
                                                     #:masr.specs{:loop-v
                                                                  "Var_45927",
                                                                  :loop-start
                                                                  #:masr.specs{:term
                                                                               :masr.specs/expr,
                                                                               :asr-expr-head
                                                                               #:masr.specs{:Integer
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/ttype,
                                                                                                         :asr-ttype-head
                                                                                                         #:masr.specs{:ttype-head
                                                                                                                      :masr.specs/Integer,
                                                                                                                      :integer-kind
                                                                                                                      4,
                                                                                                                      :dimension*
                                                                                                                      []}},
                                                                                            :int
                                                                                            0,
                                                                                            :expr-head
                                                                                            :masr.specs/IntegerConstant}},
                                                                  :loop-end
                                                                  #:masr.specs{:term
                                                                               :masr.specs/expr,
                                                                               :asr-expr-head
                                                                               #:masr.specs{:expr-head
                                                                                            :masr.specs/IntegerBinOp,
                                                                                            :integer-left
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/expr,
                                                                                                         :asr-expr-head
                                                                                                         #:masr.specs{:Integer
                                                                                                                      #:masr.specs{:term
                                                                                                                                   :masr.specs/ttype,
                                                                                                                                   :asr-ttype-head
                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                :integer-kind
                                                                                                                                                4,
                                                                                                                                                :dimension*
                                                                                                                                                []}},
                                                                                                                      :int
                                                                                                                      16,
                                                                                                                      :expr-head
                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                            :integer-binop
                                                                                            #:masr.specs{:integer-binop-enum
                                                                                                         "Sub",
                                                                                                         :term
                                                                                                         :masr.specs/integer-binop},
                                                                                            :integer-right
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/expr,
                                                                                                         :asr-expr-head
                                                                                                         #:masr.specs{:Integer
                                                                                                                      #:masr.specs{:term
                                                                                                                                   :masr.specs/ttype,
                                                                                                                                   :asr-ttype-head
                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                :integer-kind
                                                                                                                                                4,
                                                                                                                                                :dimension*
                                                                                                                                                []}},
                                                                                                                      :int
                                                                                                                      1,
                                                                                                                      :expr-head
                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                            :Integer
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/ttype,
                                                                                                         :asr-ttype-head
                                                                                                         #:masr.specs{:ttype-head
                                                                                                                      :masr.specs/Integer,
                                                                                                                      :integer-kind
                                                                                                                      4,
                                                                                                                      :dimension*
                                                                                                                      []}},
                                                                                            :integer-value?
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/expr,
                                                                                                         :asr-expr-head
                                                                                                         #:masr.specs{:Integer
                                                                                                                      #:masr.specs{:term
                                                                                                                                   :masr.specs/ttype,
                                                                                                                                   :asr-ttype-head
                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                :integer-kind
                                                                                                                                                4,
                                                                                                                                                :dimension*
                                                                                                                                                []}},
                                                                                                                      :int
                                                                                                                      15,
                                                                                                                      :expr-head
                                                                                                                      :masr.specs/IntegerConstant}}}},
                                                                  :loop-increment
                                                                  #:masr.specs{:term
                                                                               :masr.specs/expr,
                                                                               :asr-expr-head
                                                                               #:masr.specs{:Integer
                                                                                            #:masr.specs{:term
                                                                                                         :masr.specs/ttype,
                                                                                                         :asr-ttype-head
                                                                                                         #:masr.specs{:ttype-head
                                                                                                                      :masr.specs/Integer,
                                                                                                                      :integer-kind
                                                                                                                      4,
                                                                                                                      :dimension*
                                                                                                                      []}},
                                                                                            :int
                                                                                            1,
                                                                                            :expr-head
                                                                                            :masr.specs/IntegerConstant}}},
                                                     :body
                                                     ["Assignment_47646"]}}]}}

