(ns masr.resources._pass_loop_vectorise-vec_01-fdf30b1.Assignment.Assignment_90237)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_88935",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/RealBinOp,
                                                    :real-left
                                                    "Var_88938",
                                                    :real-binop
                                                    #:masr.specs{:term
                                                                 :masr.specs/real-binop,
                                                                 :real-binop-enum
                                                                 "RMul"},
                                                    :real-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/RealBinOp,
                                                                              :real-left
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/Cast,
                                                                                                        :arg
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/expr,
                                                                                                                     :asr-expr-head
                                                                                                                     #:masr.specs{:Integer
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/ttype,
                                                                                                                                               :asr-ttype-head
                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                            :masr.specs/Integer,
                                                                                                                                                            :integer-kind
                                                                                                                                                            4,
                                                                                                                                                            :dimension*
                                                                                                                                                            []}},
                                                                                                                                  :int
                                                                                                                                  180,
                                                                                                                                  :expr-head
                                                                                                                                  :masr.specs/IntegerConstant}},
                                                                                                        :cast-kind
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/cast-kind,
                                                                                                                     :cast-kind-enum
                                                                                                                     "IntegerToReal"},
                                                                                                        :ttype
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :value?
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/expr,
                                                                                                                     :asr-expr-head
                                                                                                                     #:masr.specs{:float
                                                                                                                                  180.0,
                                                                                                                                  :expr-head
                                                                                                                                  :masr.specs/RealConstant,
                                                                                                                                  :Real
                                                                                                                                  #:masr.specs{:term
                                                                                                                                               :masr.specs/ttype,
                                                                                                                                               :asr-ttype-head
                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                            :masr.specs/Real,
                                                                                                                                                            :real-kind
                                                                                                                                                            4,
                                                                                                                                                            :dimension*
                                                                                                                                                            []}}}}}},
                                                                              :real-binop
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/real-binop,
                                                                                           :real-binop-enum
                                                                                           "RDiv"},
                                                                              :real-right
                                                                              "Var_88941",
                                                                              :Real
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :real-value?
                                                                              ()}},
                                                    :Real
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Real,
                                                                              :real-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :real-value? ()}},
                          :overloaded ()}}

