(ns masr.resources.-expr13-10040d8.Assignment.Assignment_12813)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_12753",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/ComplexCompare,
                                                    :complex-left
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/FunctionCall,
                                                                              :symbol-ref
                                                                              #:masr.specs{:identifier
                                                                                           "complex__AT____lpython_overloaded_9__complex",
                                                                                           :symtab-id
                                                                                           2},
                                                                              :orig-symref
                                                                              #:masr.specs{:identifier
                                                                                           "complex",
                                                                                           :symtab-id
                                                                                           2},
                                                                              :call-args
                                                                              [[#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:Integer
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Integer,
                                                                                                                                    :integer-kind
                                                                                                                                    4,
                                                                                                                                    :dimension*
                                                                                                                                    []}},
                                                                                                          :int
                                                                                                          3,
                                                                                                          :expr-head
                                                                                                          :masr.specs/IntegerConstant}}]
                                                                               [#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:Integer
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Integer,
                                                                                                                                    :integer-kind
                                                                                                                                    4,
                                                                                                                                    :dimension*
                                                                                                                                    []}},
                                                                                                          :int
                                                                                                          4,
                                                                                                          :expr-head
                                                                                                          :masr.specs/IntegerConstant}}]],
                                                                              :return-type
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:complex-kind
                                                                                                        8,
                                                                                                        :ttype-head
                                                                                                        :masr.specs/Complex,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/ComplexConstant,
                                                                                                        :real-part
                                                                                                        3.0,
                                                                                                        :imaginary-part
                                                                                                        4.0,
                                                                                                        :Complex
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:complex-kind
                                                                                                                                  8,
                                                                                                                                  :ttype-head
                                                                                                                                  :masr.specs/Complex,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :dt?
                                                                              ()}},
                                                    :complex-cmpop
                                                    #:masr.specs{:term
                                                                 :masr.specs/complex-cmpop,
                                                                 :complex-cmpop-enum
                                                                 "CEq"},
                                                    :complex-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/FunctionCall,
                                                                              :symbol-ref
                                                                              #:masr.specs{:identifier
                                                                                           "complex__AT____lpython_overloaded_5__complex",
                                                                                           :symtab-id
                                                                                           2},
                                                                              :orig-symref
                                                                              #:masr.specs{:identifier
                                                                                           "complex",
                                                                                           :symtab-id
                                                                                           2},
                                                                              :call-args
                                                                              [[#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:float
                                                                                                          3.0,
                                                                                                          :expr-head
                                                                                                          :masr.specs/RealConstant,
                                                                                                          :Real
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    8,
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}]
                                                                               [#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:float
                                                                                                          4.0,
                                                                                                          :expr-head
                                                                                                          :masr.specs/RealConstant,
                                                                                                          :Real
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    8,
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}]],
                                                                              :return-type
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:complex-kind
                                                                                                        8,
                                                                                                        :ttype-head
                                                                                                        :masr.specs/Complex,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/ComplexConstant,
                                                                                                        :real-part
                                                                                                        3.0,
                                                                                                        :imaginary-part
                                                                                                        4.0,
                                                                                                        :Complex
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:complex-kind
                                                                                                                                  8,
                                                                                                                                  :ttype-head
                                                                                                                                  :masr.specs/Complex,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :dt?
                                                                              ()}},
                                                    :Logical
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:logical-kind
                                                                              4,
                                                                              :ttype-head
                                                                              :masr.specs/Logical,
                                                                              :dimension*
                                                                              []}},
                                                    :logical-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:Logical
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:logical-kind
                                                                                                        4,
                                                                                                        :ttype-head
                                                                                                        :masr.specs/Logical,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :expr-head
                                                                              :masr.specs/LogicalConstant,
                                                                              :bool
                                                                              true}}}},
                          :overloaded ()}}

