(ns masr.resources.-expr10-31c163f.Assignment.Assignment_11295)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_11214",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/LogicalNot,
                                                    :logical-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/Cast,
                                                                              :arg
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        5,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}},
                                                                              :cast-kind
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/cast-kind,
                                                                                           :cast-kind-enum
                                                                                           "IntegerToLogical"},
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:logical-kind
                                                                                                        4,
                                                                                                        :ttype-head
                                                                                                        :masr.specs/Logical,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Logical
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:logical-kind
                                                                                                                                  4,
                                                                                                                                  :ttype-head
                                                                                                                                  :masr.specs/Logical,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :expr-head
                                                                                                        :masr.specs/LogicalConstant,
                                                                                                        :bool
                                                                                                        false}}}},
                                                    :Logical
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:logical-kind
                                                                              4,
                                                                              :ttype-head
                                                                              :masr.specs/Logical,
                                                                              :dimension*
                                                                              []}},
                                                    :logical-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:Logical
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:logical-kind
                                                                                                        4,
                                                                                                        :ttype-head
                                                                                                        :masr.specs/Logical,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :expr-head
                                                                              :masr.specs/LogicalConstant,
                                                                              :bool
                                                                              false}}}},
                          :overloaded ()}}

