(ns masr.resources.-expr11-1134d3f.Assignment.Assignment_12006)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_11982",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/StringRepeat,
                                                    :string-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "bb",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        2,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}},
                                                    :integer-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:Integer
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :integer-value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        -40,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}},
                                                                              :expr-head
                                                                              :masr.specs/IntegerUnaryMinus,
                                                                              :integer-expr
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        40,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}}}},
                                                    :Character
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Character,
                                                                              :character-kind
                                                                              1,
                                                                              :len
                                                                              0,
                                                                              :disposition
                                                                              "compile-time-length",
                                                                              :len-expr?
                                                                              (),
                                                                              :dimension*
                                                                              []}},
                                                    :string-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        0,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

