(ns masr.resources.-expr11-1134d3f.Assignment.Assignment_12009)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_11985",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/StringRepeat,
                                                    :string-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringRepeat,
                                                                              :string-expr
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/StringConstant,
                                                                                                        :string
                                                                                                        "a",
                                                                                                        :Character
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Character,
                                                                                                                                  :character-kind
                                                                                                                                  1,
                                                                                                                                  :len
                                                                                                                                  1,
                                                                                                                                  :disposition
                                                                                                                                  "compile-time-length",
                                                                                                                                  :len-expr?
                                                                                                                                  (),
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :integer-expr
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        3,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}},
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        3,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :string-value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/StringConstant,
                                                                                                        :string
                                                                                                        "aaa",
                                                                                                        :Character
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Character,
                                                                                                                                  :character-kind
                                                                                                                                  1,
                                                                                                                                  :len
                                                                                                                                  3,
                                                                                                                                  :disposition
                                                                                                                                  "compile-time-length",
                                                                                                                                  :len-expr?
                                                                                                                                  (),
                                                                                                                                  :dimension*
                                                                                                                                  []}}}}}},
                                                    :integer-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:Integer
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :int
                                                                              3,
                                                                              :expr-head
                                                                              :masr.specs/IntegerConstant}},
                                                    :Character
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Character,
                                                                              :character-kind
                                                                              1,
                                                                              :len
                                                                              9,
                                                                              :disposition
                                                                              "compile-time-length",
                                                                              :len-expr?
                                                                              (),
                                                                              :dimension*
                                                                              []}},
                                                    :string-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "aaaaaaaaa",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        9,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

