(ns masr.resources.-test_builtin_int-990d1de.Assignment.Assignment_31944)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_31851",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/IntegerBinOp,
                                                    :integer-left
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/Cast,
                                                                              :arg
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Logical
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:logical-kind
                                                                                                                                  4,
                                                                                                                                  :ttype-head
                                                                                                                                  :masr.specs/Logical,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :expr-head
                                                                                                        :masr.specs/LogicalConstant,
                                                                                                        :bool
                                                                                                        false}},
                                                                              :cast-kind
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/cast-kind,
                                                                                           :cast-kind-enum
                                                                                           "LogicalToInteger"},
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              ()}},
                                                    :integer-binop
                                                    #:masr.specs{:integer-binop-enum
                                                                 "Add",
                                                                 :term
                                                                 :masr.specs/integer-binop},
                                                    :integer-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/Cast,
                                                                              :arg
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Logical
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:logical-kind
                                                                                                                                  4,
                                                                                                                                  :ttype-head
                                                                                                                                  :masr.specs/Logical,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :expr-head
                                                                                                        :masr.specs/LogicalConstant,
                                                                                                        :bool
                                                                                                        true}},
                                                                              :cast-kind
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/cast-kind,
                                                                                           :cast-kind-enum
                                                                                           "LogicalToInteger"},
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              ()}},
                                                    :Integer
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Integer,
                                                                              :integer-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :integer-value?
                                                    ()}},
                          :overloaded ()}}

