(ns masr.resources.-test_numpy_04-3376b7a.Function.Function_59970)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_59766"
                           "Assignment_59769"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:expr-head
                                                                                                                                   :masr.specs/IntrinsicFunction,
                                                                                                                                   :intrinsic-ident
                                                                                                                                   "Abs",
                                                                                                                                   :expr*
                                                                                                                                   [#:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/IntegerBinOp,
                                                                                                                                                              :integer-left
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:expr-head
                                                                                                                                                                                        :masr.specs/ArrayItem,
                                                                                                                                                                                        :array-expr
                                                                                                                                                                                        "Var_58200",
                                                                                                                                                                                        :array-index*
                                                                                                                                                                                        [#:masr.specs{:array-index-start?
                                                                                                                                                                                                      (),
                                                                                                                                                                                                      :array-index-end?
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:Integer
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Integer,
                                                                                                                                                                                                                                                          :integer-kind
                                                                                                                                                                                                                                                          4,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :int
                                                                                                                                                                                                                                0,
                                                                                                                                                                                                                                :expr-head
                                                                                                                                                                                                                                :masr.specs/IntegerConstant}},
                                                                                                                                                                                                      :array-index-increment?
                                                                                                                                                                                                      ()}],
                                                                                                                                                                                        :ttype
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :array-storage
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/arraystorage,
                                                                                                                                                                                                     :arraystorage-enum
                                                                                                                                                                                                     "RowMajor"},
                                                                                                                                                                                        :expr?
                                                                                                                                                                                        ()}},
                                                                                                                                                              :integer-binop
                                                                                                                                                              #:masr.specs{:integer-binop-enum
                                                                                                                                                                           "Sub",
                                                                                                                                                                           :term
                                                                                                                                                                           :masr.specs/integer-binop},
                                                                                                                                                              :integer-right
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:Integer
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :int
                                                                                                                                                                                        1,
                                                                                                                                                                                        :expr-head
                                                                                                                                                                                        :masr.specs/IntegerConstant}},
                                                                                                                                                              :Integer
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Integer,
                                                                                                                                                                                        :integer-kind
                                                                                                                                                                                        4,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :integer-value?
                                                                                                                                                              ()}}],
                                                                                                                                   :overload-id
                                                                                                                                   0,
                                                                                                                                   :return-type
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Integer,
                                                                                                                                                             :integer-kind
                                                                                                                                                             4,
                                                                                                                                                             :dimension*
                                                                                                                                                             []}},
                                                                                                                                   :value?
                                                                                                                                   ()}},
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToReal"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               "Var_58203",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:expr-head
                                                                                                                                   :masr.specs/IntrinsicFunction,
                                                                                                                                   :intrinsic-ident
                                                                                                                                   "Abs",
                                                                                                                                   :expr*
                                                                                                                                   [#:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/IntegerBinOp,
                                                                                                                                                              :integer-left
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:expr-head
                                                                                                                                                                                        :masr.specs/ArrayItem,
                                                                                                                                                                                        :array-expr
                                                                                                                                                                                        "Var_58206",
                                                                                                                                                                                        :array-index*
                                                                                                                                                                                        [#:masr.specs{:array-index-start?
                                                                                                                                                                                                      (),
                                                                                                                                                                                                      :array-index-end?
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:Integer
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Integer,
                                                                                                                                                                                                                                                          :integer-kind
                                                                                                                                                                                                                                                          4,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :int
                                                                                                                                                                                                                                1,
                                                                                                                                                                                                                                :expr-head
                                                                                                                                                                                                                                :masr.specs/IntegerConstant}},
                                                                                                                                                                                                      :array-index-increment?
                                                                                                                                                                                                      ()}],
                                                                                                                                                                                        :ttype
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :array-storage
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/arraystorage,
                                                                                                                                                                                                     :arraystorage-enum
                                                                                                                                                                                                     "RowMajor"},
                                                                                                                                                                                        :expr?
                                                                                                                                                                                        ()}},
                                                                                                                                                              :integer-binop
                                                                                                                                                              #:masr.specs{:integer-binop-enum
                                                                                                                                                                           "Sub",
                                                                                                                                                                           :term
                                                                                                                                                                           :masr.specs/integer-binop},
                                                                                                                                                              :integer-right
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:Integer
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :int
                                                                                                                                                                                        2,
                                                                                                                                                                                        :expr-head
                                                                                                                                                                                        :masr.specs/IntegerConstant}},
                                                                                                                                                              :Integer
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Integer,
                                                                                                                                                                                        :integer-kind
                                                                                                                                                                                        4,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :integer-value?
                                                                                                                                                              ()}}],
                                                                                                                                   :overload-id
                                                                                                                                   0,
                                                                                                                                   :return-type
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Integer,
                                                                                                                                                             :integer-kind
                                                                                                                                                             4,
                                                                                                                                                             :dimension*
                                                                                                                                                             []}},
                                                                                                                                   :value?
                                                                                                                                   ()}},
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToReal"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               "Var_58209",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/Cast,
                                                                                                         :arg
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:expr-head
                                                                                                                                   :masr.specs/IntrinsicFunction,
                                                                                                                                   :intrinsic-ident
                                                                                                                                   "Abs",
                                                                                                                                   :expr*
                                                                                                                                   [#:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/IntegerBinOp,
                                                                                                                                                              :integer-left
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:expr-head
                                                                                                                                                                                        :masr.specs/ArrayItem,
                                                                                                                                                                                        :array-expr
                                                                                                                                                                                        "Var_58212",
                                                                                                                                                                                        :array-index*
                                                                                                                                                                                        [#:masr.specs{:array-index-start?
                                                                                                                                                                                                      (),
                                                                                                                                                                                                      :array-index-end?
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:Integer
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Integer,
                                                                                                                                                                                                                                                          :integer-kind
                                                                                                                                                                                                                                                          4,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :int
                                                                                                                                                                                                                                2,
                                                                                                                                                                                                                                :expr-head
                                                                                                                                                                                                                                :masr.specs/IntegerConstant}},
                                                                                                                                                                                                      :array-index-increment?
                                                                                                                                                                                                      ()}],
                                                                                                                                                                                        :ttype
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :array-storage
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/arraystorage,
                                                                                                                                                                                                     :arraystorage-enum
                                                                                                                                                                                                     "RowMajor"},
                                                                                                                                                                                        :expr?
                                                                                                                                                                                        ()}},
                                                                                                                                                              :integer-binop
                                                                                                                                                              #:masr.specs{:integer-binop-enum
                                                                                                                                                                           "Sub",
                                                                                                                                                                           :term
                                                                                                                                                                           :masr.specs/integer-binop},
                                                                                                                                                              :integer-right
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:Integer
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Integer,
                                                                                                                                                                                                                  :integer-kind
                                                                                                                                                                                                                  4,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :int
                                                                                                                                                                                        3,
                                                                                                                                                                                        :expr-head
                                                                                                                                                                                        :masr.specs/IntegerConstant}},
                                                                                                                                                              :Integer
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Integer,
                                                                                                                                                                                        :integer-kind
                                                                                                                                                                                        4,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :integer-value?
                                                                                                                                                              ()}}],
                                                                                                                                   :overload-id
                                                                                                                                   0,
                                                                                                                                   :return-type
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Integer,
                                                                                                                                                             :integer-kind
                                                                                                                                                             4,
                                                                                                                                                             :dimension*
                                                                                                                                                             []}},
                                                                                                                                   :value?
                                                                                                                                   ()}},
                                                                                                         :cast-kind
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/cast-kind,
                                                                                                                      :cast-kind-enum
                                                                                                                      "IntegerToReal"},
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               "Var_58215",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}],
                          :dependencies [],
                          :deterministic false,
                          :function-signature "FunctionType_59535",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 186,
                                       :hash-map
                                       {:eps "Variable_59052",
                                        :x "Variable_59055"}},
                          :function-name "test_array_02"}}

