(ns masr.resources.-test_numpy_04-3376b7a.Function.Function_59967)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_59760"
                           "Assignment_59763"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ArrayItem,
                                                                                                                                                              :array-expr
                                                                                                                                                              "Var_58176",
                                                                                                                                                              :array-index*
                                                                                                                                                              [#:masr.specs{:array-index-start?
                                                                                                                                                                            (),
                                                                                                                                                                            :array-index-end?
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:Integer
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                                                                                                :integer-kind
                                                                                                                                                                                                                                4,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}},
                                                                                                                                                                                                      :int
                                                                                                                                                                                                      0,
                                                                                                                                                                                                      :expr-head
                                                                                                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                                                                                                            :array-index-increment?
                                                                                                                                                                            ()}],
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :array-storage
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/arraystorage,
                                                                                                                                                                           :arraystorage-enum
                                                                                                                                                                           "RowMajor"},
                                                                                                                                                              :expr?
                                                                                                                                                              ()}},
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              1.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               "Var_58179",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ArrayItem,
                                                                                                                                                              :array-expr
                                                                                                                                                              "Var_58182",
                                                                                                                                                              :array-index*
                                                                                                                                                              [#:masr.specs{:array-index-start?
                                                                                                                                                                            (),
                                                                                                                                                                            :array-index-end?
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:Integer
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                                                                                                :integer-kind
                                                                                                                                                                                                                                4,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}},
                                                                                                                                                                                                      :int
                                                                                                                                                                                                      1,
                                                                                                                                                                                                      :expr-head
                                                                                                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                                                                                                            :array-index-increment?
                                                                                                                                                                            ()}],
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :array-storage
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/arraystorage,
                                                                                                                                                                           :arraystorage-enum
                                                                                                                                                                           "RowMajor"},
                                                                                                                                                              :expr?
                                                                                                                                                              ()}},
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              2.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               "Var_58185",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ArrayItem,
                                                                                                                                                              :array-expr
                                                                                                                                                              "Var_58188",
                                                                                                                                                              :array-index*
                                                                                                                                                              [#:masr.specs{:array-index-start?
                                                                                                                                                                            (),
                                                                                                                                                                            :array-index-end?
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:Integer
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Integer,
                                                                                                                                                                                                                                :integer-kind
                                                                                                                                                                                                                                4,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}},
                                                                                                                                                                                                      :int
                                                                                                                                                                                                      2,
                                                                                                                                                                                                      :expr-head
                                                                                                                                                                                                      :masr.specs/IntegerConstant}},
                                                                                                                                                                            :array-index-increment?
                                                                                                                                                                            ()}],
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :array-storage
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/arraystorage,
                                                                                                                                                                           :arraystorage-enum
                                                                                                                                                                           "RowMajor"},
                                                                                                                                                              :expr?
                                                                                                                                                              ()}},
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:float
                                                                                                                                                              3.0,
                                                                                                                                                              :expr-head
                                                                                                                                                              :masr.specs/RealConstant,
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}}}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               "Var_58191",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}],
                          :dependencies [],
                          :deterministic false,
                          :function-signature "FunctionType_59532",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 185,
                                       :hash-map
                                       {:eps "Variable_59046",
                                        :x "Variable_59049"}},
                          :function-name "test_array_01"}}

