(ns masr.resources.-test_numpy_03-6dd742e.SymbolTable.SymbolTable_48120)


#:masr.specs{:term :masr.specs/SymbolTable,
             :symtab-id 1,
             :hash-map
             {:_global_symbols
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/Module,
                                        :SymbolTable
                                        #:masr.specs{:term
                                                     :masr.specs/SymbolTable,
                                                     :symtab-id 204,
                                                     :hash-map
                                                     {:_lpython_main_program
                                                      "Function_47886",
                                                      :test_1d_to_nd
                                                      "Function_47889",
                                                      :test_nd_to_1d
                                                      "Function_47892",
                                                      :test_reshape_with_argument
                                                      "Function_47895"}},
                                        :modulenym "_global_symbols",
                                        :dependencies
                                        ["lpython_builtin"],
                                        :loaded-from-mod false,
                                        :intrinsic false}},
              :lpython_builtin
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/IntrinsicModule,
                                        :modulenym "lpython_builtin"}},
              :main_program
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/Program,
                                        :SymbolTable
                                        #:masr.specs{:term
                                                     :masr.specs/SymbolTable,
                                                     :symtab-id 202,
                                                     :hash-map
                                                     {:_lpython_main_program
                                                      "ExternalSymbol_47835"}},
                                        :prognym "main_program",
                                        :dependencies
                                        ["_global_symbols"],
                                        :body
                                        ["SubroutineCall_47883"]}},
              :numpy
              #:masr.specs{:term :masr.specs/symbol,
                           :asr-symbol-head
                           #:masr.specs{:symbol-head
                                        :masr.specs/Module,
                                        :SymbolTable
                                        #:masr.specs{:term
                                                     :masr.specs/SymbolTable,
                                                     :symtab-id 3,
                                                     :hash-map
                                                     {:_lfortran_dlog
                                                      "Function_47898",
                                                      :__lpython_overloaded_1__sinh
                                                      "Function_47901",
                                                      :__lpython_overloaded_0__degrees
                                                      "Function_47904",
                                                      :_lfortran_dacos
                                                      "Function_47907",
                                                      :pi_64
                                                      "Variable_46890",
                                                      :ceil
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "ceil",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__ceil",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__ceil",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arcsinh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arcsinh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arcsinh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arcsinh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__arcsinh
                                                      "Function_47910",
                                                      :_lfortran_datan
                                                      "Function_47913",
                                                      :__lpython_overloaded_0__ceil
                                                      "Function_47916",
                                                      :_lfortran_stan
                                                      "Function_47919",
                                                      :_lfortran_satan
                                                      "Function_47922",
                                                      :__lpython_overloaded_0__arccos
                                                      "Function_47925",
                                                      :_lfortran_dtan
                                                      "Function_47928",
                                                      :cos
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "cos",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__cos",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__cos",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :log10
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "log10",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__log10",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__log10",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__sin
                                                      "Function_47931",
                                                      :_lfortran_ssinh
                                                      "Function_47934",
                                                      :__lpython_overloaded_0__log10
                                                      "Function_47937",
                                                      :__lpython_overloaded_0__arccosh
                                                      "Function_47940",
                                                      :_lfortran_sexp
                                                      "Function_47943",
                                                      :__lpython_overloaded_1__cos
                                                      "Function_47946",
                                                      :tan
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "tan",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__tan",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__tan",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_0__log2
                                                      "Function_47949",
                                                      :__lpython_overloaded_0__cosh
                                                      "Function_47952",
                                                      :pi_32
                                                      "Variable_46986",
                                                      :__lpython_overloaded_1__log
                                                      "Function_47955",
                                                      :arccosh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arccosh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arccosh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arccosh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_dcosh
                                                      "Function_47958",
                                                      :arcsin
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arcsin",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arcsin",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arcsin",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :sqrt
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "sqrt",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__sqrt",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__sqrt",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_scos
                                                      "Function_47961",
                                                      :_lfortran_satanh
                                                      "Function_47964",
                                                      :_lfortran_sasinh
                                                      "Function_47967",
                                                      :__lpython_overloaded_1__floor
                                                      "Function_47970",
                                                      :mod
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "mod",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__mod",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__mod",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_slog10
                                                      "Function_47973",
                                                      :__lpython_overloaded_0__log
                                                      "Function_47976",
                                                      :__lpython_overloaded_1__tan
                                                      "Function_47979",
                                                      :exp
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "exp",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__exp",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__exp",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :cosh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "cosh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__cosh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__cosh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__tanh
                                                      "Function_47982",
                                                      :__lpython_overloaded_0__arctanh
                                                      "Function_47985",
                                                      :__lpython_overloaded_1__degrees
                                                      "Function_47988",
                                                      :_lfortran_datanh
                                                      "Function_47991",
                                                      :_lfortran_slog
                                                      "Function_47994",
                                                      :__lpython_overloaded_0__sqrt
                                                      "Function_47997",
                                                      :log2
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "log2",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__log2",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__log2",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__arctan
                                                      "Function_48000",
                                                      :__lpython_overloaded_0__cos
                                                      "Function_48003",
                                                      :__lpython_overloaded_0__tan
                                                      "Function_48006",
                                                      :__lpython_overloaded_1__arcsin
                                                      "Function_48009",
                                                      :__lpython_overloaded_0__radians
                                                      "Function_48012",
                                                      :_lfortran_dcos
                                                      "Function_48015",
                                                      :__lpython_overloaded_0__arcsinh
                                                      "Function_48018",
                                                      :__lpython_overloaded_1__log2
                                                      "Function_48021",
                                                      :__lpython_overloaded_1__sqrt
                                                      "Function_48024",
                                                      :_lfortran_dacosh
                                                      "Function_48027",
                                                      :_lfortran_dasin
                                                      "Function_48030",
                                                      :__lpython_overloaded_0__arctan
                                                      "Function_48033",
                                                      :sinh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "sinh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__sinh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__sinh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arctanh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arctanh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arctanh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arctanh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :_lfortran_sasin
                                                      "Function_48036",
                                                      :__lpython_overloaded_1__ceil
                                                      "Function_48039",
                                                      :_lfortran_dasinh
                                                      "Function_48042",
                                                      :__lpython_overloaded_1__cosh
                                                      "Function_48045",
                                                      :_lfortran_dsin
                                                      "Function_48048",
                                                      :_lfortran_dtanh
                                                      "Function_48051",
                                                      :_lfortran_sacos
                                                      "Function_48054",
                                                      :__lpython_overloaded_0__sin
                                                      "Function_48057",
                                                      :sin
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "sin",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__sin",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__sin",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_1__arccos
                                                      "Function_48060",
                                                      :__lpython_overloaded_1__exp
                                                      "Function_48063",
                                                      :__lpython_overloaded_0__tanh
                                                      "Function_48066",
                                                      :_lfortran_dlog10
                                                      "Function_48069",
                                                      :_lfortran_stanh
                                                      "Function_48072",
                                                      :__lpython_overloaded_1__radians
                                                      "Function_48075",
                                                      :_lfortran_dexp
                                                      "Function_48078",
                                                      :__lpython_overloaded_1__mod
                                                      "Function_48081",
                                                      :__lpython_overloaded_0__arcsin
                                                      "Function_48084",
                                                      :_lfortran_ssin
                                                      "Function_48087",
                                                      :__lpython_overloaded_1__arccosh
                                                      "Function_48090",
                                                      :_lfortran_sacosh
                                                      "Function_48093",
                                                      :__lpython_overloaded_1__arctanh
                                                      "Function_48096",
                                                      :_lfortran_scosh
                                                      "Function_48099",
                                                      :__lpython_overloaded_0__exp
                                                      "Function_48102",
                                                      :radians
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "radians",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__radians",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__radians",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :degrees
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "degrees",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__degrees",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__degrees",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arctan
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arctan",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arctan",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arctan",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_0__sinh
                                                      "Function_48105",
                                                      :log
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "log",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__log",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__log",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :floor
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "floor",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__floor",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__floor",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :arccos
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "arccos",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__arccos",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__arccos",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :tanh
                                                      #:masr.specs{:term
                                                                   :masr.specs/symbol,
                                                                   :asr-symbol-head
                                                                   #:masr.specs{:symbol-head
                                                                                :masr.specs/GenericProcedure,
                                                                                :symtab-id
                                                                                3,
                                                                                :function-name
                                                                                "tanh",
                                                                                :symbol-ref*
                                                                                [#:masr.specs{:identifier
                                                                                              "__lpython_overloaded_0__tanh",
                                                                                              :symtab-id
                                                                                              3}
                                                                                 #:masr.specs{:identifier
                                                                                              "__lpython_overloaded_1__tanh",
                                                                                              :symtab-id
                                                                                              3}],
                                                                                :access
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/access,
                                                                                             :access-enum
                                                                                             "Public"}}},
                                                      :__lpython_overloaded_0__floor
                                                      "Function_48108",
                                                      :_lfortran_dsinh
                                                      "Function_48111",
                                                      :__lpython_overloaded_0__mod
                                                      "Function_48114",
                                                      :__lpython_overloaded_1__log10
                                                      "Function_48117"}},
                                        :modulenym "numpy",
                                        :dependencies
                                        ["lpython_builtin"],
                                        :loaded-from-mod false,
                                        :intrinsic false}}}}

