(ns masr.resources.-test_max_min-e73decc.Function.Function_44436)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_44343"
                           "Assignment_44346"
                           "Assignment_44349"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max__AT____lpython_overloaded_0__max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :call-args
                                                                                                         [["Var_44199"]
                                                                                                          ["Var_44202"]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         (),
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               "Var_44205",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max__AT____lpython_overloaded_1__max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :call-args
                                                                                                         [["Var_44208"]
                                                                                                          ["Var_44211"]
                                                                                                          ["Var_44214"]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         (),
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               "Var_44217",
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max__AT____lpython_overloaded_1__max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :call-args
                                                                                                         [[#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     1,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}}]
                                                                                                          [#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     2,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}}]
                                                                                                          [#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     3,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}}]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:Integer
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Integer,
                                                                                                                                                             :integer-kind
                                                                                                                                                             4,
                                                                                                                                                             :dimension*
                                                                                                                                                             []}},
                                                                                                                                   :int
                                                                                                                                   3,
                                                                                                                                   :expr-head
                                                                                                                                   :masr.specs/IntegerConstant}},
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Integer
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :int
                                                                                                         3,
                                                                                                         :expr-head
                                                                                                         :masr.specs/IntegerConstant}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Logical
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:logical-kind
                                                                                                                                   4,
                                                                                                                                   :ttype-head
                                                                                                                                   :masr.specs/Logical,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :expr-head
                                                                                                         :masr.specs/LogicalConstant,
                                                                                                         :bool
                                                                                                         true}}}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/IntegerCompare,
                                                                               :integer-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max__AT____lpython_overloaded_0__max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "max",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :call-args
                                                                                                         [[#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     1,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}}]
                                                                                                          [#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     6,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}}]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:Integer
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Integer,
                                                                                                                                                             :integer-kind
                                                                                                                                                             4,
                                                                                                                                                             :dimension*
                                                                                                                                                             []}},
                                                                                                                                   :int
                                                                                                                                   6,
                                                                                                                                   :expr-head
                                                                                                                                   :masr.specs/IntegerConstant}},
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :integer-cmpop
                                                                               #:masr.specs{:integer-cmpop-enum
                                                                                            "Eq",
                                                                                            :term
                                                                                            :masr.specs/integer-cmpop},
                                                                               :integer-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Integer
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Integer,
                                                                                                                                   :integer-kind
                                                                                                                                   4,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :int
                                                                                                         6,
                                                                                                         :expr-head
                                                                                                         :masr.specs/IntegerConstant}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Logical
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:logical-kind
                                                                                                                                   4,
                                                                                                                                   :ttype-head
                                                                                                                                   :masr.specs/Logical,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :expr-head
                                                                                                         :masr.specs/LogicalConstant,
                                                                                                         :bool
                                                                                                         true}}}},
                                                     :message? ()}}],
                          :dependencies
                          ["max__AT____lpython_overloaded_0__max"
                           "max__AT____lpython_overloaded_1__max"],
                          :deterministic false,
                          :function-signature "FunctionType_44325",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 2,
                                       :hash-map
                                       {:a "Variable_44289",
                                        :b "Variable_44292",
                                        :c "Variable_44295",
                                        :max "ExternalSymbol_44379",
                                        :max__AT____lpython_overloaded_0__max
                                        "ExternalSymbol_44382",
                                        :max__AT____lpython_overloaded_1__max
                                        "ExternalSymbol_44385"}},
                          :function-name "test_max_int"}}

