(ns masr.resources.-test_builtin_oct-490a98b.Function.Function_33732)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_33711"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "oct",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         (),
                                                                                                         :call-args
                                                                                                         [["Var_33693"]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         (),
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "0o42",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   4,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           "Assignment_33714"
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "oct",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         (),
                                                                                                         :call-args
                                                                                                         [["Var_33699"]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         (),
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "-0o10213",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   8,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "oct",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         (),
                                                                                                         :call-args
                                                                                                         [[#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     34,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}}]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:expr-head
                                                                                                                                   :masr.specs/StringConstant,
                                                                                                                                   :string
                                                                                                                                   "0o42",
                                                                                                                                   :Character
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Character,
                                                                                                                                                             :character-kind
                                                                                                                                                             1,
                                                                                                                                                             :len
                                                                                                                                                             4,
                                                                                                                                                             :disposition
                                                                                                                                                             "compile-time-length",
                                                                                                                                                             :len-expr?
                                                                                                                                                             (),
                                                                                                                                                             :dimension*
                                                                                                                                                             []}}}},
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "0o42",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   4,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Logical
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:logical-kind
                                                                                                                                   4,
                                                                                                                                   :ttype-head
                                                                                                                                   :masr.specs/Logical,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :expr-head
                                                                                                         :masr.specs/LogicalConstant,
                                                                                                         :bool
                                                                                                         true}}}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/StringCompare,
                                                                               :string-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/FunctionCall,
                                                                                                         :symbol-ref
                                                                                                         #:masr.specs{:identifier
                                                                                                                      "oct",
                                                                                                                      :symtab-id
                                                                                                                      2},
                                                                                                         :orig-symref
                                                                                                         (),
                                                                                                         :call-args
                                                                                                         [[#:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :integer-value?
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/expr,
                                                                                                                                                  :asr-expr-head
                                                                                                                                                  #:masr.specs{:Integer
                                                                                                                                                               #:masr.specs{:term
                                                                                                                                                                            :masr.specs/ttype,
                                                                                                                                                                            :asr-ttype-head
                                                                                                                                                                            #:masr.specs{:ttype-head
                                                                                                                                                                                         :masr.specs/Integer,
                                                                                                                                                                                         :integer-kind
                                                                                                                                                                                         4,
                                                                                                                                                                                         :dimension*
                                                                                                                                                                                         []}},
                                                                                                                                                               :int
                                                                                                                                                               -4235,
                                                                                                                                                               :expr-head
                                                                                                                                                               :masr.specs/IntegerConstant}},
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerUnaryMinus,
                                                                                                                                     :integer-expr
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/expr,
                                                                                                                                                  :asr-expr-head
                                                                                                                                                  #:masr.specs{:Integer
                                                                                                                                                               #:masr.specs{:term
                                                                                                                                                                            :masr.specs/ttype,
                                                                                                                                                                            :asr-ttype-head
                                                                                                                                                                            #:masr.specs{:ttype-head
                                                                                                                                                                                         :masr.specs/Integer,
                                                                                                                                                                                         :integer-kind
                                                                                                                                                                                         4,
                                                                                                                                                                                         :dimension*
                                                                                                                                                                                         []}},
                                                                                                                                                               :int
                                                                                                                                                               4235,
                                                                                                                                                               :expr-head
                                                                                                                                                               :masr.specs/IntegerConstant}}}}]],
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   -2,
                                                                                                                                   :disposition
                                                                                                                                   "allocatable",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/expr,
                                                                                                                      :asr-expr-head
                                                                                                                      #:masr.specs{:expr-head
                                                                                                                                   :masr.specs/StringConstant,
                                                                                                                                   :string
                                                                                                                                   "-0o10213",
                                                                                                                                   :Character
                                                                                                                                   #:masr.specs{:term
                                                                                                                                                :masr.specs/ttype,
                                                                                                                                                :asr-ttype-head
                                                                                                                                                #:masr.specs{:ttype-head
                                                                                                                                                             :masr.specs/Character,
                                                                                                                                                             :character-kind
                                                                                                                                                             1,
                                                                                                                                                             :len
                                                                                                                                                             8,
                                                                                                                                                             :disposition
                                                                                                                                                             "compile-time-length",
                                                                                                                                                             :len-expr?
                                                                                                                                                             (),
                                                                                                                                                             :dimension*
                                                                                                                                                             []}}}},
                                                                                                         :dt?
                                                                                                         ()}},
                                                                               :string-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/string-cmpop,
                                                                                            :string-cmpop-enum
                                                                                            "SEq"},
                                                                               :string-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/StringConstant,
                                                                                                         :string
                                                                                                         "-0o10213",
                                                                                                         :Character
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   8,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:Logical
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:logical-kind
                                                                                                                                   4,
                                                                                                                                   :ttype-head
                                                                                                                                   :masr.specs/Logical,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :expr-head
                                                                                                         :masr.specs/LogicalConstant,
                                                                                                         :bool
                                                                                                         true}}}},
                                                     :message? ()}}],
                          :dependencies ["oct"],
                          :deterministic false,
                          :function-signature "FunctionType_33708",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* [],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 2,
                                       :hash-map
                                       {:i "Variable_33702",
                                        :oct "ExternalSymbol_33717"}},
                          :function-name "test_oct"}}

