(ns masr.resources.-test_numpy_03-6dd742e.Function.Function_47892)


#:masr.specs{:term :masr.specs/symbol,
             :asr-symbol-head
             #:masr.specs{:symbol-head :masr.specs/Function,
                          :body
                          ["Assignment_47616"
                           "Assignment_47619"
                           "Assignment_47622"
                           "DoLoop_47859"
                           "DoLoop_47862"
                           "Assignment_47628"
                           "Assignment_47631"
                           "DoLoop_47865"],
                          :dependencies
                          ["_lpython_floordiv__AT____lpython_overloaded_4___lpython_floordiv"],
                          :deterministic false,
                          :function-signature "FunctionType_47340",
                          :side-effect-free false,
                          :access
                          #:masr.specs{:term :masr.specs/access,
                                       :access-enum "Public"},
                          :return-var? (),
                          :param* ["Var_45816"],
                          :SymbolTable
                          #:masr.specs{:term :masr.specs/SymbolTable,
                                       :symtab-id 185,
                                       :hash-map
                                       {:block
                                        #:masr.specs{:term
                                                     :masr.specs/symbol,
                                                     :asr-symbol-head
                                                     #:masr.specs{:symbol-head
                                                                  :masr.specs/Block,
                                                                  :SymbolTable
                                                                  #:masr.specs{:term
                                                                               :masr.specs/SymbolTable,
                                                                               :symtab-id
                                                                               188,
                                                                               :hash-map
                                                                               {:_lpython_floordiv
                                                                                "ExternalSymbol_47817",
                                                                                :_lpython_floordiv__AT____lpython_overloaded_4___lpython_floordiv
                                                                                "ExternalSymbol_47820"}},
                                                                  :blocknym
                                                                  "block",
                                                                  :body
                                                                  ["Assignment_47601"
                                                                   "Assignment_47604"
                                                                   #:masr.specs{:term
                                                                                :masr.specs/stmt,
                                                                                :asr-stmt-head
                                                                                #:masr.specs{:stmt-head
                                                                                             :masr.specs/Assert,
                                                                                             :test-expr
                                                                                             #:masr.specs{:term
                                                                                                          :masr.specs/expr,
                                                                                                          :asr-expr-head
                                                                                                          #:masr.specs{:expr-head
                                                                                                                       :masr.specs/RealCompare,
                                                                                                                       :real-left
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/expr,
                                                                                                                                    :asr-expr-head
                                                                                                                                    #:masr.specs{:expr-head
                                                                                                                                                 :masr.specs/IntrinsicFunction,
                                                                                                                                                 :intrinsic-ident
                                                                                                                                                 "Abs",
                                                                                                                                                 :expr*
                                                                                                                                                 [#:masr.specs{:term
                                                                                                                                                               :masr.specs/expr,
                                                                                                                                                               :asr-expr-head
                                                                                                                                                               #:masr.specs{:expr-head
                                                                                                                                                                            :masr.specs/RealBinOp,
                                                                                                                                                                            :real-left
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:expr-head
                                                                                                                                                                                                      :masr.specs/RealBinOp,
                                                                                                                                                                                                      :real-left
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:expr-head
                                                                                                                                                                                                                                :masr.specs/ArrayItem,
                                                                                                                                                                                                                                :array-expr
                                                                                                                                                                                                                                "Var_45756",
                                                                                                                                                                                                                                :array-index*
                                                                                                                                                                                                                                [#:masr.specs{:array-index-start?
                                                                                                                                                                                                                                              (),
                                                                                                                                                                                                                                              :array-index-end?
                                                                                                                                                                                                                                              "Var_45759",
                                                                                                                                                                                                                                              :array-index-increment?
                                                                                                                                                                                                                                              ()}],
                                                                                                                                                                                                                                :ttype
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Real,
                                                                                                                                                                                                                                                          :real-kind
                                                                                                                                                                                                                                                          8,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :array-storage
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/arraystorage,
                                                                                                                                                                                                                                             :arraystorage-enum
                                                                                                                                                                                                                                             "RowMajor"},
                                                                                                                                                                                                                                :expr?
                                                                                                                                                                                                                                ()}},
                                                                                                                                                                                                      :real-binop
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/real-binop,
                                                                                                                                                                                                                   :real-binop-enum
                                                                                                                                                                                                                   "RSub"},
                                                                                                                                                                                                      :real-right
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:expr-head
                                                                                                                                                                                                                                :masr.specs/Cast,
                                                                                                                                                                                                                                :arg
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/expr,
                                                                                                                                                                                                                                             :asr-expr-head
                                                                                                                                                                                                                                             #:masr.specs{:expr-head
                                                                                                                                                                                                                                                          :masr.specs/IntegerBinOp,
                                                                                                                                                                                                                                                          :integer-left
                                                                                                                                                                                                                                                          "Var_45762",
                                                                                                                                                                                                                                                          :integer-binop
                                                                                                                                                                                                                                                          #:masr.specs{:integer-binop-enum
                                                                                                                                                                                                                                                                       "Add",
                                                                                                                                                                                                                                                                       :term
                                                                                                                                                                                                                                                                       :masr.specs/integer-binop},
                                                                                                                                                                                                                                                          :integer-right
                                                                                                                                                                                                                                                          "Var_45765",
                                                                                                                                                                                                                                                          :Integer
                                                                                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                                                                                       :masr.specs/ttype,
                                                                                                                                                                                                                                                                       :asr-ttype-head
                                                                                                                                                                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                                    :masr.specs/Integer,
                                                                                                                                                                                                                                                                                    :integer-kind
                                                                                                                                                                                                                                                                                    4,
                                                                                                                                                                                                                                                                                    :dimension*
                                                                                                                                                                                                                                                                                    []}},
                                                                                                                                                                                                                                                          :integer-value?
                                                                                                                                                                                                                                                          ()}},
                                                                                                                                                                                                                                :cast-kind
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/cast-kind,
                                                                                                                                                                                                                                             :cast-kind-enum
                                                                                                                                                                                                                                             "IntegerToReal"},
                                                                                                                                                                                                                                :ttype
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Real,
                                                                                                                                                                                                                                                          :real-kind
                                                                                                                                                                                                                                                          8,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :value?
                                                                                                                                                                                                                                ()}},
                                                                                                                                                                                                      :Real
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Real,
                                                                                                                                                                                                                                :real-kind
                                                                                                                                                                                                                                8,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}},
                                                                                                                                                                                                      :real-value?
                                                                                                                                                                                                      ()}},
                                                                                                                                                                            :real-binop
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/real-binop,
                                                                                                                                                                                         :real-binop-enum
                                                                                                                                                                                         "RSub"},
                                                                                                                                                                            :real-right
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:float
                                                                                                                                                                                                      0.5,
                                                                                                                                                                                                      :expr-head
                                                                                                                                                                                                      :masr.specs/RealConstant,
                                                                                                                                                                                                      :Real
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Real,
                                                                                                                                                                                                                                :real-kind
                                                                                                                                                                                                                                8,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}}}},
                                                                                                                                                                            :Real
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/ttype,
                                                                                                                                                                                         :asr-ttype-head
                                                                                                                                                                                         #:masr.specs{:ttype-head
                                                                                                                                                                                                      :masr.specs/Real,
                                                                                                                                                                                                      :real-kind
                                                                                                                                                                                                      8,
                                                                                                                                                                                                      :dimension*
                                                                                                                                                                                                      []}},
                                                                                                                                                                            :real-value?
                                                                                                                                                                            ()}}],
                                                                                                                                                 :overload-id
                                                                                                                                                 0,
                                                                                                                                                 :return-type
                                                                                                                                                 #:masr.specs{:term
                                                                                                                                                              :masr.specs/ttype,
                                                                                                                                                              :asr-ttype-head
                                                                                                                                                              #:masr.specs{:ttype-head
                                                                                                                                                                           :masr.specs/Real,
                                                                                                                                                                           :real-kind
                                                                                                                                                                           8,
                                                                                                                                                                           :dimension*
                                                                                                                                                                           []}},
                                                                                                                                                 :value?
                                                                                                                                                 ()}},
                                                                                                                       :real-cmpop
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/real-cmpop,
                                                                                                                                    :real-cmpop-enum
                                                                                                                                    "RLtE"},
                                                                                                                       :real-right
                                                                                                                       "Var_45768",
                                                                                                                       :Logical
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/ttype,
                                                                                                                                    :asr-ttype-head
                                                                                                                                    #:masr.specs{:logical-kind
                                                                                                                                                 4,
                                                                                                                                                 :ttype-head
                                                                                                                                                 :masr.specs/Logical,
                                                                                                                                                 :dimension*
                                                                                                                                                 []}},
                                                                                                                       :logical-value?
                                                                                                                       ()}},
                                                                                             :message?
                                                                                             ()}}]}},
                                        :newshape1 "Variable_46815",
                                        :l "Variable_46818",
                                        :k "Variable_46821",
                                        :c "Variable_46824",
                                        :j "Variable_46827",
                                        :block1
                                        #:masr.specs{:term
                                                     :masr.specs/symbol,
                                                     :asr-symbol-head
                                                     #:masr.specs{:symbol-head
                                                                  :masr.specs/Block,
                                                                  :SymbolTable
                                                                  #:masr.specs{:term
                                                                               :masr.specs/SymbolTable,
                                                                               :symtab-id
                                                                               192,
                                                                               :hash-map
                                                                               {:_lpython_floordiv
                                                                                "ExternalSymbol_47823",
                                                                                :_lpython_floordiv__AT____lpython_overloaded_4___lpython_floordiv
                                                                                "ExternalSymbol_47826"}},
                                                                  :blocknym
                                                                  "block1",
                                                                  :body
                                                                  ["Assignment_47607"
                                                                   "Assignment_47610"
                                                                   "Assignment_47613"
                                                                   #:masr.specs{:term
                                                                                :masr.specs/stmt,
                                                                                :asr-stmt-head
                                                                                #:masr.specs{:stmt-head
                                                                                             :masr.specs/Assert,
                                                                                             :test-expr
                                                                                             #:masr.specs{:term
                                                                                                          :masr.specs/expr,
                                                                                                          :asr-expr-head
                                                                                                          #:masr.specs{:expr-head
                                                                                                                       :masr.specs/RealCompare,
                                                                                                                       :real-left
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/expr,
                                                                                                                                    :asr-expr-head
                                                                                                                                    #:masr.specs{:expr-head
                                                                                                                                                 :masr.specs/IntrinsicFunction,
                                                                                                                                                 :intrinsic-ident
                                                                                                                                                 "Abs",
                                                                                                                                                 :expr*
                                                                                                                                                 [#:masr.specs{:term
                                                                                                                                                               :masr.specs/expr,
                                                                                                                                                               :asr-expr-head
                                                                                                                                                               #:masr.specs{:expr-head
                                                                                                                                                                            :masr.specs/RealBinOp,
                                                                                                                                                                            :real-left
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:expr-head
                                                                                                                                                                                                      :masr.specs/RealBinOp,
                                                                                                                                                                                                      :real-left
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:expr-head
                                                                                                                                                                                                                                :masr.specs/ArrayItem,
                                                                                                                                                                                                                                :array-expr
                                                                                                                                                                                                                                "Var_45798",
                                                                                                                                                                                                                                :array-index*
                                                                                                                                                                                                                                [#:masr.specs{:array-index-start?
                                                                                                                                                                                                                                              (),
                                                                                                                                                                                                                                              :array-index-end?
                                                                                                                                                                                                                                              "Var_45801",
                                                                                                                                                                                                                                              :array-index-increment?
                                                                                                                                                                                                                                              ()}],
                                                                                                                                                                                                                                :ttype
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Real,
                                                                                                                                                                                                                                                          :real-kind
                                                                                                                                                                                                                                                          8,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :array-storage
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/arraystorage,
                                                                                                                                                                                                                                             :arraystorage-enum
                                                                                                                                                                                                                                             "RowMajor"},
                                                                                                                                                                                                                                :expr?
                                                                                                                                                                                                                                ()}},
                                                                                                                                                                                                      :real-binop
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/real-binop,
                                                                                                                                                                                                                   :real-binop-enum
                                                                                                                                                                                                                   "RSub"},
                                                                                                                                                                                                      :real-right
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/expr,
                                                                                                                                                                                                                   :asr-expr-head
                                                                                                                                                                                                                   #:masr.specs{:expr-head
                                                                                                                                                                                                                                :masr.specs/Cast,
                                                                                                                                                                                                                                :arg
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/expr,
                                                                                                                                                                                                                                             :asr-expr-head
                                                                                                                                                                                                                                             #:masr.specs{:expr-head
                                                                                                                                                                                                                                                          :masr.specs/IntegerBinOp,
                                                                                                                                                                                                                                                          :integer-left
                                                                                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                                                                                       :masr.specs/expr,
                                                                                                                                                                                                                                                                       :asr-expr-head
                                                                                                                                                                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                                                                                                                                                                    :masr.specs/IntegerBinOp,
                                                                                                                                                                                                                                                                                    :integer-left
                                                                                                                                                                                                                                                                                    "Var_45804",
                                                                                                                                                                                                                                                                                    :integer-binop
                                                                                                                                                                                                                                                                                    #:masr.specs{:integer-binop-enum
                                                                                                                                                                                                                                                                                                 "Add",
                                                                                                                                                                                                                                                                                                 :term
                                                                                                                                                                                                                                                                                                 :masr.specs/integer-binop},
                                                                                                                                                                                                                                                                                    :integer-right
                                                                                                                                                                                                                                                                                    "Var_45807",
                                                                                                                                                                                                                                                                                    :Integer
                                                                                                                                                                                                                                                                                    #:masr.specs{:term
                                                                                                                                                                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                                                                                                                                                                 :asr-ttype-head
                                                                                                                                                                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                                                              :masr.specs/Integer,
                                                                                                                                                                                                                                                                                                              :integer-kind
                                                                                                                                                                                                                                                                                                              4,
                                                                                                                                                                                                                                                                                                              :dimension*
                                                                                                                                                                                                                                                                                                              []}},
                                                                                                                                                                                                                                                                                    :integer-value?
                                                                                                                                                                                                                                                                                    ()}},
                                                                                                                                                                                                                                                          :integer-binop
                                                                                                                                                                                                                                                          #:masr.specs{:integer-binop-enum
                                                                                                                                                                                                                                                                       "Add",
                                                                                                                                                                                                                                                                       :term
                                                                                                                                                                                                                                                                       :masr.specs/integer-binop},
                                                                                                                                                                                                                                                          :integer-right
                                                                                                                                                                                                                                                          "Var_45810",
                                                                                                                                                                                                                                                          :Integer
                                                                                                                                                                                                                                                          #:masr.specs{:term
                                                                                                                                                                                                                                                                       :masr.specs/ttype,
                                                                                                                                                                                                                                                                       :asr-ttype-head
                                                                                                                                                                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                                                    :masr.specs/Integer,
                                                                                                                                                                                                                                                                                    :integer-kind
                                                                                                                                                                                                                                                                                    4,
                                                                                                                                                                                                                                                                                    :dimension*
                                                                                                                                                                                                                                                                                    []}},
                                                                                                                                                                                                                                                          :integer-value?
                                                                                                                                                                                                                                                          ()}},
                                                                                                                                                                                                                                :cast-kind
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/cast-kind,
                                                                                                                                                                                                                                             :cast-kind-enum
                                                                                                                                                                                                                                             "IntegerToReal"},
                                                                                                                                                                                                                                :ttype
                                                                                                                                                                                                                                #:masr.specs{:term
                                                                                                                                                                                                                                             :masr.specs/ttype,
                                                                                                                                                                                                                                             :asr-ttype-head
                                                                                                                                                                                                                                             #:masr.specs{:ttype-head
                                                                                                                                                                                                                                                          :masr.specs/Real,
                                                                                                                                                                                                                                                          :real-kind
                                                                                                                                                                                                                                                          8,
                                                                                                                                                                                                                                                          :dimension*
                                                                                                                                                                                                                                                          []}},
                                                                                                                                                                                                                                :value?
                                                                                                                                                                                                                                ()}},
                                                                                                                                                                                                      :Real
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Real,
                                                                                                                                                                                                                                :real-kind
                                                                                                                                                                                                                                8,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}},
                                                                                                                                                                                                      :real-value?
                                                                                                                                                                                                      ()}},
                                                                                                                                                                            :real-binop
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/real-binop,
                                                                                                                                                                                         :real-binop-enum
                                                                                                                                                                                         "RSub"},
                                                                                                                                                                            :real-right
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/expr,
                                                                                                                                                                                         :asr-expr-head
                                                                                                                                                                                         #:masr.specs{:float
                                                                                                                                                                                                      0.5,
                                                                                                                                                                                                      :expr-head
                                                                                                                                                                                                      :masr.specs/RealConstant,
                                                                                                                                                                                                      :Real
                                                                                                                                                                                                      #:masr.specs{:term
                                                                                                                                                                                                                   :masr.specs/ttype,
                                                                                                                                                                                                                   :asr-ttype-head
                                                                                                                                                                                                                   #:masr.specs{:ttype-head
                                                                                                                                                                                                                                :masr.specs/Real,
                                                                                                                                                                                                                                :real-kind
                                                                                                                                                                                                                                8,
                                                                                                                                                                                                                                :dimension*
                                                                                                                                                                                                                                []}}}},
                                                                                                                                                                            :Real
                                                                                                                                                                            #:masr.specs{:term
                                                                                                                                                                                         :masr.specs/ttype,
                                                                                                                                                                                         :asr-ttype-head
                                                                                                                                                                                         #:masr.specs{:ttype-head
                                                                                                                                                                                                      :masr.specs/Real,
                                                                                                                                                                                                      :real-kind
                                                                                                                                                                                                      8,
                                                                                                                                                                                                      :dimension*
                                                                                                                                                                                                      []}},
                                                                                                                                                                            :real-value?
                                                                                                                                                                            ()}}],
                                                                                                                                                 :overload-id
                                                                                                                                                 0,
                                                                                                                                                 :return-type
                                                                                                                                                 #:masr.specs{:term
                                                                                                                                                              :masr.specs/ttype,
                                                                                                                                                              :asr-ttype-head
                                                                                                                                                              #:masr.specs{:ttype-head
                                                                                                                                                                           :masr.specs/Real,
                                                                                                                                                                           :real-kind
                                                                                                                                                                           8,
                                                                                                                                                                           :dimension*
                                                                                                                                                                           []}},
                                                                                                                                                 :value?
                                                                                                                                                 ()}},
                                                                                                                       :real-cmpop
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/real-cmpop,
                                                                                                                                    :real-cmpop-enum
                                                                                                                                    "RLtE"},
                                                                                                                       :real-right
                                                                                                                       "Var_45813",
                                                                                                                       :Logical
                                                                                                                       #:masr.specs{:term
                                                                                                                                    :masr.specs/ttype,
                                                                                                                                    :asr-ttype-head
                                                                                                                                    #:masr.specs{:logical-kind
                                                                                                                                                 4,
                                                                                                                                                 :ttype-head
                                                                                                                                                 :masr.specs/Logical,
                                                                                                                                                 :dimension*
                                                                                                                                                 []}},
                                                                                                                       :logical-value?
                                                                                                                       ()}},
                                                                                             :message?
                                                                                             ()}}]}},
                                        :b "Variable_46830",
                                        :d "Variable_46833",
                                        :newshape "Variable_46836",
                                        :i "Variable_46839",
                                        :a "Variable_46842",
                                        :eps "Variable_46845"}},
                          :function-name "test_nd_to_1d"}}

