(ns masr.resources.-test_complex_01-c199562.Assignment.Assignment_40152)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_39942",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/FunctionCall,
                                                    :symbol-ref
                                                    #:masr.specs{:identifier
                                                                 "complex__AT____lpython_overloaded_5__complex",
                                                                 :symtab-id
                                                                 4},
                                                    :orig-symref
                                                    #:masr.specs{:identifier
                                                                 "complex",
                                                                 :symtab-id
                                                                 4},
                                                    :call-args
                                                    [[#:masr.specs{:term
                                                                   :masr.specs/expr,
                                                                   :asr-expr-head
                                                                   #:masr.specs{:real-value?
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:float
                                                                                                          -4.5,
                                                                                                          :expr-head
                                                                                                          :masr.specs/RealConstant,
                                                                                                          :Real
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    8,
                                                                                                                                    :dimension*
                                                                                                                                    []}}}},
                                                                                :real-expr
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:float
                                                                                                          4.5,
                                                                                                          :expr-head
                                                                                                          :masr.specs/RealConstant,
                                                                                                          :Real
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    8,
                                                                                                                                    :dimension*
                                                                                                                                    []}}}},
                                                                                :expr-head
                                                                                :masr.specs/RealUnaryMinus,
                                                                                :Real
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/ttype,
                                                                                             :asr-ttype-head
                                                                                             #:masr.specs{:ttype-head
                                                                                                          :masr.specs/Real,
                                                                                                          :real-kind
                                                                                                          8,
                                                                                                          :dimension*
                                                                                                          []}}}}]
                                                     [#:masr.specs{:term
                                                                   :masr.specs/expr,
                                                                   :asr-expr-head
                                                                   #:masr.specs{:real-value?
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:float
                                                                                                          -7.8,
                                                                                                          :expr-head
                                                                                                          :masr.specs/RealConstant,
                                                                                                          :Real
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    8,
                                                                                                                                    :dimension*
                                                                                                                                    []}}}},
                                                                                :real-expr
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:float
                                                                                                          7.8,
                                                                                                          :expr-head
                                                                                                          :masr.specs/RealConstant,
                                                                                                          :Real
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    8,
                                                                                                                                    :dimension*
                                                                                                                                    []}}}},
                                                                                :expr-head
                                                                                :masr.specs/RealUnaryMinus,
                                                                                :Real
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/ttype,
                                                                                             :asr-ttype-head
                                                                                             #:masr.specs{:ttype-head
                                                                                                          :masr.specs/Real,
                                                                                                          :real-kind
                                                                                                          8,
                                                                                                          :dimension*
                                                                                                          []}}}}]],
                                                    :return-type
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:complex-kind
                                                                              8,
                                                                              :ttype-head
                                                                              :masr.specs/Complex,
                                                                              :dimension*
                                                                              []}},
                                                    :value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/ComplexConstant,
                                                                              :real-part
                                                                              -4.5,
                                                                              :imaginary-part
                                                                              -7.8,
                                                                              :Complex
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:complex-kind
                                                                                                        8,
                                                                                                        :ttype-head
                                                                                                        :masr.specs/Complex,
                                                                                                        :dimension*
                                                                                                        []}}}},
                                                    :dt? ()}},
                          :overloaded ()}}

