(ns masr.resources.-test_complex_01-c199562.Assignment.Assignment_40095)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_39807",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:real-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:float
                                                                              -423.543081,
                                                                              :expr-head
                                                                              :masr.specs/RealConstant,
                                                                              :Real
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}}}},
                                                    :real-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/Cast,
                                                                              :arg
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:float
                                                                                                        423.543081,
                                                                                                        :expr-head
                                                                                                        :masr.specs/RealConstant,
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :cast-kind
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/cast-kind,
                                                                                           :cast-kind-enum
                                                                                           "RealToReal"},
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:float
                                                                                                        423.543081,
                                                                                                        :expr-head
                                                                                                        :masr.specs/RealConstant,
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}}}},
                                                    :expr-head
                                                    :masr.specs/RealUnaryMinus,
                                                    :Real
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Real,
                                                                              :real-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}}}},
                          :overloaded ()}}

