(ns masr.resources.-test_complex_01-c199562.Assignment.Assignment_40107)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_39831",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:Integer
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Integer,
                                                                              :integer-kind
                                                                              8,
                                                                              :dimension*
                                                                              []}},
                                                    :integer-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:Integer
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        8,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :int
                                                                              -6,
                                                                              :expr-head
                                                                              :masr.specs/IntegerConstant}},
                                                    :expr-head
                                                    :masr.specs/IntegerUnaryMinus,
                                                    :integer-expr
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/Cast,
                                                                              :arg
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  4,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        6,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}},
                                                                              :cast-kind
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/cast-kind,
                                                                                           :cast-kind-enum
                                                                                           "IntegerToInteger"},
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Integer,
                                                                                                        :integer-kind
                                                                                                        8,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:Integer
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Integer,
                                                                                                                                  :integer-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}},
                                                                                                        :int
                                                                                                        6,
                                                                                                        :expr-head
                                                                                                        :masr.specs/IntegerConstant}}}}}},
                          :overloaded ()}}

