(ns masr.resources._pass_print_list_tuple-print_02-1bcc4ec.Assignment.Assignment_81675)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_80781",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/ListConstant,
                                                    :expr*
                                                    [#:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/ListConstant,
                                                                               :expr*
                                                                               [#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "bat",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    3,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "ball",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    4,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}],
                                                                               :ttype
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/List,
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   3,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}}}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/ListConstant,
                                                                               :expr*
                                                                               [#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "cat",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    3,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "dog",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    3,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}],
                                                                               :ttype
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/List,
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   3,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}}}}
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/ListConstant,
                                                                               :expr*
                                                                               [#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "c",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    1,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "c++",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    3,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "java",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    4,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}
                                                                                #:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/StringConstant,
                                                                                                          :string
                                                                                                          "python",
                                                                                                          :Character
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Character,
                                                                                                                                    :character-kind
                                                                                                                                    1,
                                                                                                                                    :len
                                                                                                                                    6,
                                                                                                                                    :disposition
                                                                                                                                    "compile-time-length",
                                                                                                                                    :len-expr?
                                                                                                                                    (),
                                                                                                                                    :dimension*
                                                                                                                                    []}}}}],
                                                                               :ttype
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:ttype-head
                                                                                                         :masr.specs/List,
                                                                                                         :ttype
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Character,
                                                                                                                                   :character-kind
                                                                                                                                   1,
                                                                                                                                   :len
                                                                                                                                   1,
                                                                                                                                   :disposition
                                                                                                                                   "compile-time-length",
                                                                                                                                   :len-expr?
                                                                                                                                   (),
                                                                                                                                   :dimension*
                                                                                                                                   []}}}}}}],
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/List,
                                                                              :ttype
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/List,
                                                                                                        :ttype
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Character,
                                                                                                                                  :character-kind
                                                                                                                                  1,
                                                                                                                                  :len
                                                                                                                                  3,
                                                                                                                                  :disposition
                                                                                                                                  "compile-time-length",
                                                                                                                                  :len-expr?
                                                                                                                                  (),
                                                                                                                                  :dimension*
                                                                                                                                  []}}}}}}}},
                          :overloaded ()}}

