(ns masr.resources._pass_loop_vectorise-vec_01-fdf30b1.DoLoop.DoLoop_90354)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/DoLoop,
                          :escape-target (),
                          :do-loop-head
                          #:masr.specs{:loop-v "Var_88581",
                                       :loop-start
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 0,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}},
                                       :loop-end
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 1151,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}},
                                       :loop-increment
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 1,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}}},
                          :body
                          [#:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/SubroutineCall,
                                                     :symbol-ref
                                                     #:masr.specs{:identifier
                                                                  "vector_copy_f64f64i32__AT__IntrinsicOptimization",
                                                                  :symtab-id
                                                                  185},
                                                     :orig-symref (),
                                                     :call-args
                                                     [["Var_88584"]
                                                      ["Var_88587"]
                                                      [#:masr.specs{:term
                                                                    :masr.specs/expr,
                                                                    :asr-expr-head
                                                                    #:masr.specs{:expr-head
                                                                                 :masr.specs/IntegerBinOp,
                                                                                 :integer-left
                                                                                 "Var_88590",
                                                                                 :integer-binop
                                                                                 #:masr.specs{:integer-binop-enum
                                                                                              "Mul",
                                                                                              :term
                                                                                              :masr.specs/integer-binop},
                                                                                 :integer-right
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/expr,
                                                                                              :asr-expr-head
                                                                                              #:masr.specs{:Integer
                                                                                                           #:masr.specs{:term
                                                                                                                        :masr.specs/ttype,
                                                                                                                        :asr-ttype-head
                                                                                                                        #:masr.specs{:ttype-head
                                                                                                                                     :masr.specs/Integer,
                                                                                                                                     :integer-kind
                                                                                                                                     4,
                                                                                                                                     :dimension*
                                                                                                                                     []}},
                                                                                                           :int
                                                                                                           8,
                                                                                                           :expr-head
                                                                                                           :masr.specs/IntegerConstant}},
                                                                                 :Integer
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/ttype,
                                                                                              :asr-ttype-head
                                                                                              #:masr.specs{:ttype-head
                                                                                                           :masr.specs/Integer,
                                                                                                           :integer-kind
                                                                                                           4,
                                                                                                           :dimension*
                                                                                                           []}},
                                                                                 :integer-value?
                                                                                 ()}}]
                                                      [#:masr.specs{:term
                                                                    :masr.specs/expr,
                                                                    :asr-expr-head
                                                                    #:masr.specs{:expr-head
                                                                                 :masr.specs/IntegerBinOp,
                                                                                 :integer-left
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/expr,
                                                                                              :asr-expr-head
                                                                                              #:masr.specs{:expr-head
                                                                                                           :masr.specs/IntegerBinOp,
                                                                                                           :integer-left
                                                                                                           "Var_88593",
                                                                                                           :integer-binop
                                                                                                           #:masr.specs{:integer-binop-enum
                                                                                                                        "Add",
                                                                                                                        :term
                                                                                                                        :masr.specs/integer-binop},
                                                                                                           :integer-right
                                                                                                           #:masr.specs{:term
                                                                                                                        :masr.specs/expr,
                                                                                                                        :asr-expr-head
                                                                                                                        #:masr.specs{:Integer
                                                                                                                                     #:masr.specs{:term
                                                                                                                                                  :masr.specs/ttype,
                                                                                                                                                  :asr-ttype-head
                                                                                                                                                  #:masr.specs{:ttype-head
                                                                                                                                                               :masr.specs/Integer,
                                                                                                                                                               :integer-kind
                                                                                                                                                               4,
                                                                                                                                                               :dimension*
                                                                                                                                                               []}},
                                                                                                                                     :int
                                                                                                                                     1,
                                                                                                                                     :expr-head
                                                                                                                                     :masr.specs/IntegerConstant}},
                                                                                                           :Integer
                                                                                                           #:masr.specs{:term
                                                                                                                        :masr.specs/ttype,
                                                                                                                        :asr-ttype-head
                                                                                                                        #:masr.specs{:ttype-head
                                                                                                                                     :masr.specs/Integer,
                                                                                                                                     :integer-kind
                                                                                                                                     4,
                                                                                                                                     :dimension*
                                                                                                                                     []}},
                                                                                                           :integer-value?
                                                                                                           ()}},
                                                                                 :integer-binop
                                                                                 #:masr.specs{:integer-binop-enum
                                                                                              "Mul",
                                                                                              :term
                                                                                              :masr.specs/integer-binop},
                                                                                 :integer-right
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/expr,
                                                                                              :asr-expr-head
                                                                                              #:masr.specs{:Integer
                                                                                                           #:masr.specs{:term
                                                                                                                        :masr.specs/ttype,
                                                                                                                        :asr-ttype-head
                                                                                                                        #:masr.specs{:ttype-head
                                                                                                                                     :masr.specs/Integer,
                                                                                                                                     :integer-kind
                                                                                                                                     4,
                                                                                                                                     :dimension*
                                                                                                                                     []}},
                                                                                                           :int
                                                                                                           8,
                                                                                                           :expr-head
                                                                                                           :masr.specs/IntegerConstant}},
                                                                                 :Integer
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/ttype,
                                                                                              :asr-ttype-head
                                                                                              #:masr.specs{:ttype-head
                                                                                                           :masr.specs/Integer,
                                                                                                           :integer-kind
                                                                                                           4,
                                                                                                           :dimension*
                                                                                                           []}},
                                                                                 :integer-value?
                                                                                 ()}}]
                                                      [#:masr.specs{:term
                                                                    :masr.specs/expr,
                                                                    :asr-expr-head
                                                                    #:masr.specs{:Integer
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/ttype,
                                                                                              :asr-ttype-head
                                                                                              #:masr.specs{:ttype-head
                                                                                                           :masr.specs/Integer,
                                                                                                           :integer-kind
                                                                                                           4,
                                                                                                           :dimension*
                                                                                                           []}},
                                                                                 :int
                                                                                 1,
                                                                                 :expr-head
                                                                                 :masr.specs/IntegerConstant}}]
                                                      [#:masr.specs{:term
                                                                    :masr.specs/expr,
                                                                    :asr-expr-head
                                                                    #:masr.specs{:Integer
                                                                                 #:masr.specs{:term
                                                                                              :masr.specs/ttype,
                                                                                              :asr-ttype-head
                                                                                              #:masr.specs{:ttype-head
                                                                                                           :masr.specs/Integer,
                                                                                                           :integer-kind
                                                                                                           4,
                                                                                                           :dimension*
                                                                                                           []}},
                                                                                 :int
                                                                                 8,
                                                                                 :expr-head
                                                                                 :masr.specs/IntegerConstant}}]],
                                                     :dt? ()}}]}}

