(ns masr.resources.-expr5-375548a.Assignment.Assignment_14121)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_14106",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/StringConcat,
                                                    :string-left
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConcat,
                                                                              :string-left
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/StringConstant,
                                                                                                        :string
                                                                                                        "test",
                                                                                                        :Character
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Character,
                                                                                                                                  :character-kind
                                                                                                                                  1,
                                                                                                                                  :len
                                                                                                                                  4,
                                                                                                                                  :disposition
                                                                                                                                  "compile-time-length",
                                                                                                                                  :len-expr?
                                                                                                                                  (),
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :string-right
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/StringConstant,
                                                                                                        :string
                                                                                                        "test",
                                                                                                        :Character
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Character,
                                                                                                                                  :character-kind
                                                                                                                                  1,
                                                                                                                                  :len
                                                                                                                                  4,
                                                                                                                                  :disposition
                                                                                                                                  "compile-time-length",
                                                                                                                                  :len-expr?
                                                                                                                                  (),
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        8,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :string-value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:expr-head
                                                                                                        :masr.specs/StringConstant,
                                                                                                        :string
                                                                                                        "testtest",
                                                                                                        :Character
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Character,
                                                                                                                                  :character-kind
                                                                                                                                  1,
                                                                                                                                  :len
                                                                                                                                  8,
                                                                                                                                  :disposition
                                                                                                                                  "compile-time-length",
                                                                                                                                  :len-expr?
                                                                                                                                  (),
                                                                                                                                  :dimension*
                                                                                                                                  []}}}}}},
                                                    :string-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "test",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        4,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}},
                                                    :Character
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Character,
                                                                              :character-kind
                                                                              1,
                                                                              :len
                                                                              12,
                                                                              :disposition
                                                                              "compile-time-length",
                                                                              :len-expr?
                                                                              (),
                                                                              :dimension*
                                                                              []}},
                                                    :string-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "testtesttest",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        12,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

