(ns masr.resources.-expr5-375548a.Assignment.Assignment_14115)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_14100",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/StringConcat,
                                                    :string-left
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "3",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        1,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}},
                                                    :string-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "4",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        1,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}},
                                                    :Character
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Character,
                                                                              :character-kind
                                                                              1,
                                                                              :len
                                                                              2,
                                                                              :disposition
                                                                              "compile-time-length",
                                                                              :len-expr?
                                                                              (),
                                                                              :dimension*
                                                                              []}},
                                                    :string-value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/StringConstant,
                                                                              :string
                                                                              "34",
                                                                              :Character
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Character,
                                                                                                        :character-kind
                                                                                                        1,
                                                                                                        :len
                                                                                                        2,
                                                                                                        :disposition
                                                                                                        "compile-time-length",
                                                                                                        :len-expr?
                                                                                                        (),
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

