(ns masr.resources.-test_numpy_04-3376b7a.Assignment.Assignment_59859)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_58668",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/RealBinOp,
                                                    :real-left
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/FunctionCall,
                                                                              :symbol-ref
                                                                              #:masr.specs{:identifier
                                                                                           "_lfortran_slog",
                                                                                           :symtab-id
                                                                                           3},
                                                                              :orig-symref
                                                                              (),
                                                                              :call-args
                                                                              [["Var_58671"]],
                                                                              :return-type
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              (),
                                                                              :dt?
                                                                              ()}},
                                                    :real-binop
                                                    #:masr.specs{:term
                                                                 :masr.specs/real-binop,
                                                                 :real-binop-enum
                                                                 "RDiv"},
                                                    :real-right
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/FunctionCall,
                                                                              :symbol-ref
                                                                              #:masr.specs{:identifier
                                                                                           "_lfortran_slog",
                                                                                           :symtab-id
                                                                                           3},
                                                                              :orig-symref
                                                                              (),
                                                                              :call-args
                                                                              [[#:masr.specs{:term
                                                                                             :masr.specs/expr,
                                                                                             :asr-expr-head
                                                                                             #:masr.specs{:expr-head
                                                                                                          :masr.specs/Cast,
                                                                                                          :arg
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:float
                                                                                                                                    2.0,
                                                                                                                                    :expr-head
                                                                                                                                    :masr.specs/RealConstant,
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}}}},
                                                                                                          :cast-kind
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/cast-kind,
                                                                                                                       :cast-kind-enum
                                                                                                                       "RealToReal"},
                                                                                                          :ttype
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/ttype,
                                                                                                                       :asr-ttype-head
                                                                                                                       #:masr.specs{:ttype-head
                                                                                                                                    :masr.specs/Real,
                                                                                                                                    :real-kind
                                                                                                                                    4,
                                                                                                                                    :dimension*
                                                                                                                                    []}},
                                                                                                          :value?
                                                                                                          #:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:float
                                                                                                                                    2.0,
                                                                                                                                    :expr-head
                                                                                                                                    :masr.specs/RealConstant,
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              4,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}}}}}}]],
                                                                              :return-type
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :value?
                                                                              (),
                                                                              :dt?
                                                                              ()}},
                                                    :Real
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Real,
                                                                              :real-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :real-value? ()}},
                          :overloaded ()}}

