(ns masr.resources.-expr8-2a4630a.Assignment.Assignment_15141)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/Assignment,
                          :lvalue "Var_15072",
                          :rvalue
                          #:masr.specs{:term :masr.specs/expr,
                                       :asr-expr-head
                                       #:masr.specs{:expr-head
                                                    :masr.specs/Cast,
                                                    :arg
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:expr-head
                                                                              :masr.specs/RealBinOp,
                                                                              :real-left
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:float
                                                                                                        5346.565,
                                                                                                        :expr-head
                                                                                                        :masr.specs/RealConstant,
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :real-binop
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/real-binop,
                                                                                           :real-binop-enum
                                                                                           "RMul"},
                                                                              :real-right
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:float
                                                                                                        3.45,
                                                                                                        :expr-head
                                                                                                        :masr.specs/RealConstant,
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}},
                                                                              :Real
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        8,
                                                                                                        :dimension*
                                                                                                        []}},
                                                                              :real-value?
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/expr,
                                                                                           :asr-expr-head
                                                                                           #:masr.specs{:float
                                                                                                        18445.64925,
                                                                                                        :expr-head
                                                                                                        :masr.specs/RealConstant,
                                                                                                        :Real
                                                                                                        #:masr.specs{:term
                                                                                                                     :masr.specs/ttype,
                                                                                                                     :asr-ttype-head
                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                  :masr.specs/Real,
                                                                                                                                  :real-kind
                                                                                                                                  8,
                                                                                                                                  :dimension*
                                                                                                                                  []}}}}}},
                                                    :cast-kind
                                                    #:masr.specs{:term
                                                                 :masr.specs/cast-kind,
                                                                 :cast-kind-enum
                                                                 "RealToReal"},
                                                    :ttype
                                                    #:masr.specs{:term
                                                                 :masr.specs/ttype,
                                                                 :asr-ttype-head
                                                                 #:masr.specs{:ttype-head
                                                                              :masr.specs/Real,
                                                                              :real-kind
                                                                              4,
                                                                              :dimension*
                                                                              []}},
                                                    :value?
                                                    #:masr.specs{:term
                                                                 :masr.specs/expr,
                                                                 :asr-expr-head
                                                                 #:masr.specs{:float
                                                                              18445.64925,
                                                                              :expr-head
                                                                              :masr.specs/RealConstant,
                                                                              :Real
                                                                              #:masr.specs{:term
                                                                                           :masr.specs/ttype,
                                                                                           :asr-ttype-head
                                                                                           #:masr.specs{:ttype-head
                                                                                                        :masr.specs/Real,
                                                                                                        :real-kind
                                                                                                        4,
                                                                                                        :dimension*
                                                                                                        []}}}}}},
                          :overloaded ()}}

