(ns masr.resources.-expr_09-0e8c1e6.DoLoop.DoLoop_20781)


#:masr.specs{:term :masr.specs/stmt,
             :asr-stmt-head
             #:masr.specs{:stmt-head :masr.specs/DoLoop,
                          :escape-target (),
                          :do-loop-head
                          #:masr.specs{:loop-v "Var_20625",
                                       :loop-start
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 0,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}},
                                       :loop-end
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:expr-head
                                                                 :masr.specs/IntegerBinOp,
                                                                 :integer-left
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           10,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}},
                                                                 :integer-binop
                                                                 #:masr.specs{:integer-binop-enum
                                                                              "Sub",
                                                                              :term
                                                                              :masr.specs/integer-binop},
                                                                 :integer-right
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           1,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}},
                                                                 :Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :integer-value?
                                                                 #:masr.specs{:term
                                                                              :masr.specs/expr,
                                                                              :asr-expr-head
                                                                              #:masr.specs{:Integer
                                                                                           #:masr.specs{:term
                                                                                                        :masr.specs/ttype,
                                                                                                        :asr-ttype-head
                                                                                                        #:masr.specs{:ttype-head
                                                                                                                     :masr.specs/Integer,
                                                                                                                     :integer-kind
                                                                                                                     4,
                                                                                                                     :dimension*
                                                                                                                     []}},
                                                                                           :int
                                                                                           9,
                                                                                           :expr-head
                                                                                           :masr.specs/IntegerConstant}}}},
                                       :loop-increment
                                       #:masr.specs{:term
                                                    :masr.specs/expr,
                                                    :asr-expr-head
                                                    #:masr.specs{:Integer
                                                                 #:masr.specs{:term
                                                                              :masr.specs/ttype,
                                                                              :asr-ttype-head
                                                                              #:masr.specs{:ttype-head
                                                                                           :masr.specs/Integer,
                                                                                           :integer-kind
                                                                                           4,
                                                                                           :dimension*
                                                                                           []}},
                                                                 :int
                                                                 1,
                                                                 :expr-head
                                                                 :masr.specs/IntegerConstant}}},
                          :body
                          [#:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ListItem,
                                                                                                                                                              :list-expr
                                                                                                                                                              "Var_20628",
                                                                                                                                                              :index
                                                                                                                                                              "Var_20631",
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :value?
                                                                                                                                                              ()}},
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ListItem,
                                                                                                                                                              :list-expr
                                                                                                                                                              "Var_20634",
                                                                                                                                                              :index
                                                                                                                                                              "Var_20637",
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :value?
                                                                                                                                                              ()}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         0.0,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ListItem,
                                                                                                                                                              :list-expr
                                                                                                                                                              "Var_20640",
                                                                                                                                                              :index
                                                                                                                                                              "Var_20643",
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :value?
                                                                                                                                                              ()}},
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ListItem,
                                                                                                                                                              :list-expr
                                                                                                                                                              "Var_20646",
                                                                                                                                                              :index
                                                                                                                                                              "Var_20649",
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :value?
                                                                                                                                                              ()}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         0.0,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}
                           #:masr.specs{:term :masr.specs/stmt,
                                        :asr-stmt-head
                                        #:masr.specs{:stmt-head
                                                     :masr.specs/Assert,
                                                     :test-expr
                                                     #:masr.specs{:term
                                                                  :masr.specs/expr,
                                                                  :asr-expr-head
                                                                  #:masr.specs{:expr-head
                                                                               :masr.specs/RealCompare,
                                                                               :real-left
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:expr-head
                                                                                                         :masr.specs/IntrinsicFunction,
                                                                                                         :intrinsic-ident
                                                                                                         "Abs",
                                                                                                         :expr*
                                                                                                         [#:masr.specs{:term
                                                                                                                       :masr.specs/expr,
                                                                                                                       :asr-expr-head
                                                                                                                       #:masr.specs{:expr-head
                                                                                                                                    :masr.specs/RealBinOp,
                                                                                                                                    :real-left
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/RealBinOp,
                                                                                                                                                              :real-left
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:expr-head
                                                                                                                                                                                        :masr.specs/RealBinOp,
                                                                                                                                                                                        :real-left
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/expr,
                                                                                                                                                                                                     :asr-expr-head
                                                                                                                                                                                                     #:masr.specs{:expr-head
                                                                                                                                                                                                                  :masr.specs/Cast,
                                                                                                                                                                                                                  :arg
                                                                                                                                                                                                                  "Var_20652",
                                                                                                                                                                                                                  :cast-kind
                                                                                                                                                                                                                  #:masr.specs{:term
                                                                                                                                                                                                                               :masr.specs/cast-kind,
                                                                                                                                                                                                                               :cast-kind-enum
                                                                                                                                                                                                                               "IntegerToReal"},
                                                                                                                                                                                                                  :ttype
                                                                                                                                                                                                                  #:masr.specs{:term
                                                                                                                                                                                                                               :masr.specs/ttype,
                                                                                                                                                                                                                               :asr-ttype-head
                                                                                                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                                                                                                            :masr.specs/Real,
                                                                                                                                                                                                                                            :real-kind
                                                                                                                                                                                                                                            8,
                                                                                                                                                                                                                                            :dimension*
                                                                                                                                                                                                                                            []}},
                                                                                                                                                                                                                  :value?
                                                                                                                                                                                                                  ()}},
                                                                                                                                                                                        :real-binop
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/real-binop,
                                                                                                                                                                                                     :real-binop-enum
                                                                                                                                                                                                     "RMul"},
                                                                                                                                                                                        :real-right
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/expr,
                                                                                                                                                                                                     :asr-expr-head
                                                                                                                                                                                                     #:masr.specs{:float
                                                                                                                                                                                                                  2.0,
                                                                                                                                                                                                                  :expr-head
                                                                                                                                                                                                                  :masr.specs/RealConstant,
                                                                                                                                                                                                                  :Real
                                                                                                                                                                                                                  #:masr.specs{:term
                                                                                                                                                                                                                               :masr.specs/ttype,
                                                                                                                                                                                                                               :asr-ttype-head
                                                                                                                                                                                                                               #:masr.specs{:ttype-head
                                                                                                                                                                                                                                            :masr.specs/Real,
                                                                                                                                                                                                                                            :real-kind
                                                                                                                                                                                                                                            8,
                                                                                                                                                                                                                                            :dimension*
                                                                                                                                                                                                                                            []}}}},
                                                                                                                                                                                        :Real
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Real,
                                                                                                                                                                                                                  :real-kind
                                                                                                                                                                                                                  8,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}},
                                                                                                                                                                                        :real-value?
                                                                                                                                                                                        ()}},
                                                                                                                                                              :real-binop
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/real-binop,
                                                                                                                                                                           :real-binop-enum
                                                                                                                                                                           "RAdd"},
                                                                                                                                                              :real-right
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/expr,
                                                                                                                                                                           :asr-expr-head
                                                                                                                                                                           #:masr.specs{:float
                                                                                                                                                                                        5.0,
                                                                                                                                                                                        :expr-head
                                                                                                                                                                                        :masr.specs/RealConstant,
                                                                                                                                                                                        :Real
                                                                                                                                                                                        #:masr.specs{:term
                                                                                                                                                                                                     :masr.specs/ttype,
                                                                                                                                                                                                     :asr-ttype-head
                                                                                                                                                                                                     #:masr.specs{:ttype-head
                                                                                                                                                                                                                  :masr.specs/Real,
                                                                                                                                                                                                                  :real-kind
                                                                                                                                                                                                                  8,
                                                                                                                                                                                                                  :dimension*
                                                                                                                                                                                                                  []}}}},
                                                                                                                                                              :Real
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :real-value?
                                                                                                                                                              ()}},
                                                                                                                                    :real-binop
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/real-binop,
                                                                                                                                                 :real-binop-enum
                                                                                                                                                 "RSub"},
                                                                                                                                    :real-right
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/expr,
                                                                                                                                                 :asr-expr-head
                                                                                                                                                 #:masr.specs{:expr-head
                                                                                                                                                              :masr.specs/ListItem,
                                                                                                                                                              :list-expr
                                                                                                                                                              "Var_20655",
                                                                                                                                                              :index
                                                                                                                                                              "Var_20658",
                                                                                                                                                              :ttype
                                                                                                                                                              #:masr.specs{:term
                                                                                                                                                                           :masr.specs/ttype,
                                                                                                                                                                           :asr-ttype-head
                                                                                                                                                                           #:masr.specs{:ttype-head
                                                                                                                                                                                        :masr.specs/Real,
                                                                                                                                                                                        :real-kind
                                                                                                                                                                                        8,
                                                                                                                                                                                        :dimension*
                                                                                                                                                                                        []}},
                                                                                                                                                              :value?
                                                                                                                                                              ()}},
                                                                                                                                    :Real
                                                                                                                                    #:masr.specs{:term
                                                                                                                                                 :masr.specs/ttype,
                                                                                                                                                 :asr-ttype-head
                                                                                                                                                 #:masr.specs{:ttype-head
                                                                                                                                                              :masr.specs/Real,
                                                                                                                                                              :real-kind
                                                                                                                                                              8,
                                                                                                                                                              :dimension*
                                                                                                                                                              []}},
                                                                                                                                    :real-value?
                                                                                                                                    ()}}],
                                                                                                         :overload-id
                                                                                                         0,
                                                                                                         :return-type
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}},
                                                                                                         :value?
                                                                                                         ()}},
                                                                               :real-cmpop
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/real-cmpop,
                                                                                            :real-cmpop-enum
                                                                                            "RLt"},
                                                                               :real-right
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/expr,
                                                                                            :asr-expr-head
                                                                                            #:masr.specs{:float
                                                                                                         0.0,
                                                                                                         :expr-head
                                                                                                         :masr.specs/RealConstant,
                                                                                                         :Real
                                                                                                         #:masr.specs{:term
                                                                                                                      :masr.specs/ttype,
                                                                                                                      :asr-ttype-head
                                                                                                                      #:masr.specs{:ttype-head
                                                                                                                                   :masr.specs/Real,
                                                                                                                                   :real-kind
                                                                                                                                   8,
                                                                                                                                   :dimension*
                                                                                                                                   []}}}},
                                                                               :Logical
                                                                               #:masr.specs{:term
                                                                                            :masr.specs/ttype,
                                                                                            :asr-ttype-head
                                                                                            #:masr.specs{:logical-kind
                                                                                                         4,
                                                                                                         :ttype-head
                                                                                                         :masr.specs/Logical,
                                                                                                         :dimension*
                                                                                                         []}},
                                                                               :logical-value?
                                                                               ()}},
                                                     :message? ()}}]}}

